In [12]:
import pandas as pd

df = pd.read_csv("career_training_data_cleaned (1).csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (2000, 32)

,field_filter,hobby_coding,hobby_gaming,hobby_reading,hobby_writing,hobby_music,hobby_drawing_art,hobby_sports,hobby_cooking,hobby_photography,...,score_analytical,score_numeric,score_verbal,score_creative,score_social,top_career_1,top_career_2,top_career_3,top_career_4,top_career_5
0,all,0,0,0,0,0,1,0,0,0,...,96,97,62,78,66,Data Analyst,Data Scientist,Cybersecurity Analyst,Database Administrator,Systems Analyst
1,Defense,1,0,0,0,0,0,1,0,0,...,88,65,80,63,77,Defense Scientist,Navy Officer,Army Officer,Air Force Officer,Coast Guard Officer
2,all,0,0,1,1,0,0,0,0,0,...,74,77,91,81,92,Accountant,Chartered Accountant (CA),Marketing Manager,Human Resource Manager,Operations Manager
3,Forensics,0,0,1,0,1,0,0,0,0,...,60,64,56,67,68,Criminologist,Forensic Scientist,Crime Scene Investigator,Forensic Psychologist,Digital Forensics Analyst
4,all,1,0,1,1,0,1,0,0,0,...,75,57,76,58,65,Public Relations Manager,IT Project Manager,Animator,Film Director,Video Editor

In [13]:
from google.colab import files

uploaded = files.upload()

Saving career_training_data_cleaned.csv to career_training_data_cleaned (2).csv

In [14]:
import os

print(os.listdir())

['.config', 'career_training_data_cleaned (2).csv', 'career_training_data_cleaned (1).csv', 'career_training_data_cleaned.csv', 'sample_data']

In [15]:
import pandas as pd
import os

csv_files = [f for f in os.listdir() if f.endswith(".csv")]

print("CSV files found:", csv_files)

df = pd.read_csv(csv_files[0])

print("Dataset loaded successfully!")
print("Shape:", df.shape)

CSV files found: ['career_training_data_cleaned (2).csv', 'career_training_data_cleaned (1).csv', 'career_training_data_cleaned.csv']
Dataset loaded successfully!
Shape: (2000, 32)

In [16]:
df.shape

(2000, 32)

In [17]:
df.columns.tolist()

['field_filter',
 'hobby_coding',
 'hobby_gaming',
 'hobby_reading',
 'hobby_writing',
 'hobby_music',
 'hobby_drawing_art',
 'hobby_sports',
 'hobby_cooking',
 'hobby_photography',
 'hobby_travel',
 'hobby_science_experiments',
 'hobby_volunteering',
 'hobby_debating',
 'hobby_robotics',
 'hobby_fashion',
 'hobby_business_trading',
 'grade_math',
 'grade_science',
 'grade_lang',
 'grade_social',
 'grade_cs',
 'score_analytical',
 'score_numeric',
 'score_verbal',
 'score_creative',
 'score_social',
 'top_career_1',
 'top_career_2',
 'top_career_3',
 'top_career_4',
 'top_career_5']

In [18]:
df.isnull().sum()

field_filter                 0
hobby_coding                 0
hobby_gaming                 0
hobby_reading                0
hobby_writing                0
hobby_music                  0
hobby_drawing_art            0
hobby_sports                 0
hobby_cooking                0
hobby_photography            0
hobby_travel                 0
hobby_science_experiments    0
hobby_volunteering           0
hobby_debating               0
hobby_robotics               0
hobby_fashion                0
hobby_business_trading       0
grade_math                   0
grade_science                0
grade_lang                   0
grade_social                 0
grade_cs                     0
score_analytical             0
score_numeric                0
score_verbal                 0
score_creative               0
score_social                 0
top_career_1                 0
top_career_2                 0
top_career_3                 0
top_career_4                 0
top_career_5                 0
dtype: int64

In [19]:
feature_columns = [
    "field_filter",

    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading",

    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs",

    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"
]

In [20]:
target_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]

In [21]:
X = df[feature_columns]

y = df[target_columns]

In [22]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2000, 27)
y shape: (2000, 5)

In [23]:
import pandas as pd

df = pd.read_csv("/content/career_training_data_cleaned.csv")

print("Dataset shape:", df.shape)

print("\nColumns:")
for col in df.columns:
    print(col)

print("\nCareer recommendation columns:")
print(df[
    [
        "top_career_1",
        "top_career_2",
        "top_career_3",
        "top_career_4",
        "top_career_5"
    ]
].head(10))

Dataset shape: (2000, 32)

Columns:
field_filter
hobby_coding
hobby_gaming
hobby_reading
hobby_writing
hobby_music
hobby_drawing_art
hobby_sports
hobby_cooking
hobby_photography
hobby_travel
hobby_science_experiments
hobby_volunteering
hobby_debating
hobby_robotics
hobby_fashion
hobby_business_trading
grade_math
grade_science
grade_lang
grade_social
grade_cs
score_analytical
score_numeric
score_verbal
score_creative
score_social
top_career_1
top_career_2
top_career_3
top_career_4
top_career_5

Career recommendation columns:
                    top_career_1               top_career_2  \
0                   Data Analyst             Data Scientist
1              Defense Scientist               Navy Officer
2                     Accountant  Chartered Accountant (CA)
3                  Criminologist         Forensic Scientist
4       Public Relations Manager         IT Project Manager
5         Social Welfare Officer          Lawyer / Advocate
6       Public Relations Manager         IT Project Manager
7              Financial Analyst           Business Analyst
8  Aircraft Maintenance Engineer                      Pilot
9         Social Welfare Officer          Lawyer / Advocate

               top_career_3            top_career_4               top_career_5
0     Cybersecurity Analyst  Database Administrator            Systems Analyst
1              Army Officer       Air Force Officer        Coast Guard Officer
2         Marketing Manager  Human Resource Manager         Operations Manager
3  Crime Scene Investigator   Forensic Psychologist  Digital Forensics Analyst
4                  Animator           Film Director               Video Editor
5                     Judge           Legal Advisor          Public Prosecutor
6          Training Manager              Accountant  Chartered Accountant (CA)
7              Risk Analyst          Credit Analyst               Data Analyst
8          Commercial Pilot  Air Traffic Controller          Flight Dispatcher
9                     Judge           Legal Advisor          Public Prosecutor

In [24]:
print("\nNumber of unique careers:")

all_careers = pd.concat([
    df["top_career_1"],
    df["top_career_2"],
    df["top_career_3"],
    df["top_career_4"],
    df["top_career_5"]
])

print(all_careers.nunique())

print("\nMost common careers:")
print(all_careers.value_counts().head(30))

Number of unique careers:
141

Most common careers:
Accountant                   271
Chartered Accountant (CA)    267
Network Engineer             216
IT Project Manager           213
Marketing Manager            212
Cloud Engineer               203
Public Relations Manager     189
Human Resource Manager       173
Graphic Designer             164
AI Engineer                  163
Machine Learning Engineer    159
Training Manager             153
Film Director                136
Video Editor                 136
Animator                     136
Interior Designer            136
Operations Manager           135
Fashion Designer             133
Web Developer                129
Mobile App Developer         129
Software Developer           129
Journalist                   118
DevOps Engineer              114
Data Scientist               113
School Teacher               106
Professor                    105
Special Education Teacher    102
Nurse                         99
Pharmacist                    99
Doctor                        99
Name: count, dtype: int64

In [25]:
print("\nNumber of unique careers:")

all_careers = pd.concat([
    df["top_career_1"],
    df["top_career_2"],
    df["top_career_3"],
    df["top_career_4"],
    df["top_career_5"]
])

print(all_careers.nunique())

print("\nMost common careers:")
print(all_careers.value_counts().head(30))

Number of unique careers:
141

Most common careers:
Accountant                   271
Chartered Accountant (CA)    267
Network Engineer             216
IT Project Manager           213
Marketing Manager            212
Cloud Engineer               203
Public Relations Manager     189
Human Resource Manager       173
Graphic Designer             164
AI Engineer                  163
Machine Learning Engineer    159
Training Manager             153
Film Director                136
Video Editor                 136
Animator                     136
Interior Designer            136
Operations Manager           135
Fashion Designer             133
Web Developer                129
Mobile App Developer         129
Software Developer           129
Journalist                   118
DevOps Engineer              114
Data Scientist               113
School Teacher               106
Professor                    105
Special Education Teacher    102
Nurse                         99
Pharmacist                    99
Doctor                        99
Name: count, dtype: int64

In [26]:
# Check missing values in every column

missing = df.isnull().sum()

print("Missing values:")
print(missing[missing > 0])

Missing values:
Series([], dtype: int64)

In [27]:
# Check blank strings

print("Blank values:")
for col in df.columns:
    blanks = (df[col].astype(str).str.strip() == "").sum()
    if blanks > 0:
        print(col, ":", blanks)

Blank values:

In [28]:
df.isnull().sum()

field_filter                 0
hobby_coding                 0
hobby_gaming                 0
hobby_reading                0
hobby_writing                0
hobby_music                  0
hobby_drawing_art            0
hobby_sports                 0
hobby_cooking                0
hobby_photography            0
hobby_travel                 0
hobby_science_experiments    0
hobby_volunteering           0
hobby_debating               0
hobby_robotics               0
hobby_fashion                0
hobby_business_trading       0
grade_math                   0
grade_science                0
grade_lang                   0
grade_social                 0
grade_cs                     0
score_analytical             0
score_numeric                0
score_verbal                 0
score_creative               0
score_social                 0
top_career_1                 0
top_career_2                 0
top_career_3                 0
top_career_4                 0
top_career_5                 0
dtype: int64

In [29]:
# Top 5 career recommendation columns

target_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]

# Input columns
input_columns = [
    col for col in df.columns
    if col not in target_columns
]

print("INPUT COLUMNS:")
for col in input_columns:
    print(col)

print("\nTARGET COLUMNS:")
for col in target_columns:
    print(col)

print("\nNumber of input columns:", len(input_columns))
print("Number of target columns:", len(target_columns))

INPUT COLUMNS:
field_filter
hobby_coding
hobby_gaming
hobby_reading
hobby_writing
hobby_music
hobby_drawing_art
hobby_sports
hobby_cooking
hobby_photography
hobby_travel
hobby_science_experiments
hobby_volunteering
hobby_debating
hobby_robotics
hobby_fashion
hobby_business_trading
grade_math
grade_science
grade_lang
grade_social
grade_cs
score_analytical
score_numeric
score_verbal
score_creative
score_social

TARGET COLUMNS:
top_career_1
top_career_2
top_career_3
top_career_4
top_career_5

Number of input columns: 27
Number of target columns: 5

In [30]:
# Show a few sample records

df[input_columns + target_columns].head()

,field_filter,hobby_coding,hobby_gaming,hobby_reading,hobby_writing,hobby_music,hobby_drawing_art,hobby_sports,hobby_cooking,hobby_photography,...,score_analytical,score_numeric,score_verbal,score_creative,score_social,top_career_1,top_career_2,top_career_3,top_career_4,top_career_5
0,all,0,0,0,0,0,1,0,0,0,...,96,97,62,78,66,Data Analyst,Data Scientist,Cybersecurity Analyst,Database Administrator,Systems Analyst
1,Defense,1,0,0,0,0,0,1,0,0,...,88,65,80,63,77,Defense Scientist,Navy Officer,Army Officer,Air Force Officer,Coast Guard Officer
2,all,0,0,1,1,0,0,0,0,0,...,74,77,91,81,92,Accountant,Chartered Accountant (CA),Marketing Manager,Human Resource Manager,Operations Manager
3,Forensics,0,0,1,0,1,0,0,0,0,...,60,64,56,67,68,Criminologist,Forensic Scientist,Crime Scene Investigator,Forensic Psychologist,Digital Forensics Analyst
4,all,1,0,1,1,0,1,0,0,0,...,75,57,76,58,65,Public Relations Manager,IT Project Manager,Animator,Film Director,Video Editor

In [31]:
print("DATA TYPES")
print("=" * 50)

print(df.dtypes)

DATA TYPES
==================================================
field_filter                 object
hobby_coding                  int64
hobby_gaming                  int64
hobby_reading                 int64
hobby_writing                 int64
hobby_music                   int64
hobby_drawing_art             int64
hobby_sports                  int64
hobby_cooking                 int64
hobby_photography             int64
hobby_travel                  int64
hobby_science_experiments     int64
hobby_volunteering            int64
hobby_debating                int64
hobby_robotics                int64
hobby_fashion                 int64
hobby_business_trading        int64
grade_math                    int64
grade_science                 int64
grade_lang                    int64
grade_social                  int64
grade_cs                      int64
score_analytical              int64
score_numeric                 int64
score_verbal                  int64
score_creative                int64
score_social                  int64
top_career_1                 object
top_career_2                 object
top_career_3                 object
top_career_4                 object
top_career_5                 object
dtype: object

In [32]:
print("\nCOLUMN SUMMARY")
print("=" * 50)

for col in df.columns:
    print(f"{col:30} | {df[col].dtype}")

COLUMN SUMMARY
==================================================
field_filter                   | object
hobby_coding                   | int64
hobby_gaming                   | int64
hobby_reading                  | int64
hobby_writing                  | int64
hobby_music                    | int64
hobby_drawing_art              | int64
hobby_sports                   | int64
hobby_cooking                  | int64
hobby_photography              | int64
hobby_travel                   | int64
hobby_science_experiments      | int64
hobby_volunteering             | int64
hobby_debating                 | int64
hobby_robotics                 | int64
hobby_fashion                  | int64
hobby_business_trading         | int64
grade_math                     | int64
grade_science                  | int64
grade_lang                     | int64
grade_social                   | int64
grade_cs                       | int64
score_analytical               | int64
score_numeric                  | int64
score_verbal                   | int64
score_creative                 | int64
score_social                   | int64
top_career_1                   | object
top_career_2                   | object
top_career_3                   | object
top_career_4                   | object
top_career_5                   | object

In [33]:
# Separate input columns by data type

numeric_features = df[input_columns].select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = df[input_columns].select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("NUMERIC FEATURES")
print("=" * 50)

for col in numeric_features:
    print(col)

print("\nTotal numeric features:", len(numeric_features))


print("\nCATEGORICAL FEATURES")
print("=" * 50)

for col in categorical_features:
    print(col)

print("\nTotal categorical features:", len(categorical_features))

NUMERIC FEATURES
==================================================
hobby_coding
hobby_gaming
hobby_reading
hobby_writing
hobby_music
hobby_drawing_art
hobby_sports
hobby_cooking
hobby_photography
hobby_travel
hobby_science_experiments
hobby_volunteering
hobby_debating
hobby_robotics
hobby_fashion
hobby_business_trading
grade_math
grade_science
grade_lang
grade_social
grade_cs
score_analytical
score_numeric
score_verbal
score_creative
score_social

Total numeric features: 26

CATEGORICAL FEATURES
==================================================
field_filter

Total categorical features: 1

In [34]:
print("CATEGORICAL VALUE COUNTS")
print("=" * 50)

for col in categorical_features:
    print(f"\n{col}")
    print(df[col].nunique(), "unique values")
    print(df[col].dropna().unique()[:15])

CATEGORICAL VALUE COUNTS
==================================================

field_filter
20 unique values
['all' 'Defense' 'Forensics' 'Law & Government' 'Aviation' 'Education'
 'Fashion' 'Biotech' 'Research' 'Space Science' 'Engineering'
 'Hospitality' 'Healthcare' 'Business & Finance' 'Sports / Fitness']

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# =========================================================
# PREPROCESSING
# =========================================================

preprocessor = ColumnTransformer(
    transformers=[

        # Numerical columns
        (
            "num",
            StandardScaler(),
            numeric_features
        ),

        # Categorical columns
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        )
    ]
)

print("Preprocessor created successfully!")

Preprocessor created successfully!

In [36]:
print("Numeric features:", len(numeric_features))
print("Categorical features:", len(categorical_features))

print("\nPreprocessing is ready.")

Numeric features: 26
Categorical features: 1

Preprocessing is ready.

In [37]:
# =========================================================
# PREPARE TARGETS
# =========================================================

from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for target in target_columns:

    le = LabelEncoder()

    df[target] = le.fit_transform(
        df[target].astype(str)
    )

    label_encoders[target] = le

print("Target encoding completed!")

Target encoding completed!

In [38]:
# Check encoded target values

for target in target_columns:

    print("\n", target)
    print("Number of careers:", len(label_encoders[target].classes_))
    print("Sample careers:")

    for career in label_encoders[target].classes_[:10]:
        print(" -", career)

 top_career_1
Number of careers: 46
Sample careers:
 - Accountant
 - Agricultural Scientist
 - Aircraft Maintenance Engineer
 - Animator
 - Architect
 - Astronomer
 - Biomedical Engineer
 - Biomedical Scientist
 - Civil Engineer
 - College Lecturer

 top_career_2
Number of careers: 57
Sample careers:
 - Academic Counselor
 - Accountant
 - Agricultural Scientist
 - Animator
 - Army Officer
 - Auditor
 - Biotechnologist
 - Business Analyst
 - Chartered Accountant (CA)
 - Chemist

 top_career_3
Number of careers: 65
Sample careers:
 - AI Engineer
 - Academic Counselor
 - Accountant
 - Air Force Officer
 - Air Traffic Controller
 - Airline Manager
 - Animator
 - Army Officer
 - Biomedical Engineer
 - Biotechnologist

 top_career_4
Number of careers: 70
Sample careers:
 - AI Engineer
 - Accountant
 - Agricultural Scientist
 - Air Force Officer
 - Air Traffic Controller
 - Aircraft Maintenance Engineer
 - Airline Manager
 - Architect
 - Astronomer
 - Banking Officer

 top_career_5
Number of careers: 72
Sample careers:
 - AI Engineer
 - Academic Counselor
 - Accountant
 - Aerospace Engineer
 - Aircraft Maintenance Engineer
 - Biomedical Engineer
 - Biomedical Scientist
 - Biotechnologist
 - Chartered Accountant (CA)
 - Chemical Engineer

In [39]:
# =========================================================
# CREATE X AND Y
# =========================================================

X = df[input_columns]

Y = df[target_columns]

print("X shape:", X.shape)
print("Y shape:", Y.shape)

print("\nInput data:")
print(X.head())

print("\nTarget data:")
print(Y.head())

X shape: (2000, 27)
Y shape: (2000, 5)

Input data:
  field_filter  hobby_coding  hobby_gaming  hobby_reading  hobby_writing  \
0          all             0             0              0              0
1      Defense             1             0              0              0
2          all             0             0              1              1
3    Forensics             0             0              1              0
4          all             1             0              1              1

   hobby_music  hobby_drawing_art  hobby_sports  hobby_cooking  \
0            0                  1             0              0
1            0                  0             1              0
2            0                  0             0              0
3            1                  0             0              0
4            0                  1             0              0

   hobby_photography  ...  grade_math  grade_science  grade_lang  \
0                  0  ...          97             89          62
1                  0  ...          63             73          76
2                  0  ...          55             67          72
3                  0  ...          57             85          48
4                  0  ...          65             61          71

   grade_social  grade_cs  score_analytical  score_numeric  score_verbal  \
0            56        80                96             97            62
1            87        67                88             65            80
2            97        70                74             77            91
3            60        69                60             64            56
4            68        64                75             57            76

   score_creative  score_social
0              78            66
1              63            77
2              81            92
3              67            68
4              58            65

[5 rows x 27 columns]

Target data:
   top_career_1  top_career_2  top_career_3  top_career_4  top_career_5
0            12            16            15            20            65
1            13            36             7             3            12
2             0             8            40            32            51
3            11            25            14            28            22
4            33            29             6            25            70

In [40]:
# =========================================================
# TRAIN / TEST SPLIT
# =========================================================

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1600
Testing samples: 400

In [41]:
# =========================================================
# TRAIN RANDOM FOREST MODELS
# =========================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier

# Create the Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

# Handle the 5 career targets
model = MultiOutputClassifier(rf_model)

# Preprocess training data
X_train_processed = preprocessor.fit_transform(X_train)

print("Training model...")

# Train
model.fit(
    X_train_processed,
    Y_train
)

print("✅ Model training completed!")

Training model...
✅ Model training completed!

In [42]:
# =========================================================
# PREPARE TEST DATA
# =========================================================

X_test_processed = preprocessor.transform(X_test)

# Make predictions
Y_pred = model.predict(X_test_processed)

print("Prediction completed!")

print("Prediction shape:", Y_pred.shape)
print("Actual shape:", Y_test.shape)

Prediction completed!
Prediction shape: (400, 5)
Actual shape: (400, 5)

In [43]:
# =========================================================
# ACCURACY FOR EACH TOP CAREER
# =========================================================

from sklearn.metrics import accuracy_score

print("CAREER RECOMMENDATION ACCURACY")
print("=" * 50)

accuracies = {}

for i, target in enumerate(target_columns):

    accuracy = accuracy_score(
        Y_test.iloc[:, i],
        Y_pred[:, i]
    )

    accuracies[target] = accuracy

    print(
        f"{target}: {accuracy * 100:.2f}%"
    )

CAREER RECOMMENDATION ACCURACY
==================================================
top_career_1: 76.75%
top_career_2: 70.75%
top_career_3: 70.75%
top_career_4: 68.00%
top_career_5: 69.75%

In [44]:
# =========================================================
# TRY EXTRA TREES MODEL
# =========================================================

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.multioutput import MultiOutputClassifier

extra_model = ExtraTreesClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

extra_model = MultiOutputClassifier(extra_model)

print("Training Extra Trees model...")

extra_model.fit(
    X_train_processed,
    Y_train
)

print("✅ Extra Trees training completed!")

Training Extra Trees model...
✅ Extra Trees training completed!

In [45]:
# =========================================================
# EXTRA TREES PREDICTION
# =========================================================

Y_pred_extra = extra_model.predict(
    X_test_processed
)

print("Prediction completed!")
print("Prediction shape:", Y_pred_extra.shape)

Prediction completed!
Prediction shape: (400, 5)

In [46]:
  # =========================================================
# EXTRA TREES ACCURACY
# =========================================================

extra_accuracies = {}

print("EXTRA TREES ACCURACY")
print("=" * 50)

for i, target in enumerate(target_columns):

    accuracy = accuracy_score(
        Y_test.iloc[:, i],
        Y_pred_extra[:, i]
    )

    extra_accuracies[target] = accuracy

    print(
        f"{target}: {accuracy * 100:.2f}%"
    )

extra_average = (
    sum(extra_accuracies.values())
    / len(extra_accuracies)
)

print("=" * 50)
print(
    f"Average Accuracy: {extra_average * 100:.2f}%"
)

EXTRA TREES ACCURACY
==================================================
top_career_1: 73.25%
top_career_2: 68.75%
top_career_3: 68.50%
top_career_4: 65.25%
top_career_5: 69.00%
==================================================
Average Accuracy: 68.95%

In [47]:
career_columns = [
    'top_career_1',
    'top_career_2',
    'top_career_3',
    'top_career_4',
    'top_career_5'
]

print("CAREER DATASET CHECK")
print("=" * 50)

for col in career_columns:
    print(f"\n{col}")
    print("Blank values:", df[col].isna().sum())
    print("Unique careers:", df[col].nunique())

print("\nDataset shape:", df.shape)

CAREER DATASET CHECK
==================================================

top_career_1
Blank values: 0
Unique careers: 46

top_career_2
Blank values: 0
Unique careers: 57

top_career_3
Blank values: 0
Unique careers: 65

top_career_4
Blank values: 0
Unique careers: 70

top_career_5
Blank values: 0
Unique careers: 72

Dataset shape: (2000, 32)

In [48]:
for col in career_columns:
    print("\n" + "=" * 50)
    print(col)
    print("=" * 50)

    print(df[col].value_counts().head(15))

==================================================
top_career_1
==================================================
top_career_1
22    160
33    156
0     140
29    117
39    108
20     73
40     68
41     68
34     66
3      62
30     58
8      57
15     56
37     54
21     49
Name: count, dtype: int64

==================================================
top_career_2
==================================================
top_career_2
8     140
10    117
56    108
16     95
21     83
23     68
28     68
22     62
45     60
9      58
35     57
3      56
38     55
29     53
33     49
Name: count, dtype: int64

==================================================
top_career_3
==================================================
top_career_3
40    135
0     117
43    108
32    105
39     73
64     68
16     68
51     66
62     62
14     61
41     58
49     58
22     57
27     56
60     55
Name: count, dtype: int64

==================================================
top_career_4
==================================================
top_career_4
32    135
41    117
48     73
8      68
62     68
38     66
29     63
36     62
28     61
59     58
63     58
61     58
23     57
67     56
1      55
Name: count, dtype: int64

==================================================
top_career_5
==================================================
top_career_5
51    135
20    114
49     73
3      69
64     68
12     67
59     66
27     64
62     63
14     62
22     61
47     59
33     58
69     58
9      57
Name: count, dtype: int64

In [49]:
for col in career_columns:
    print("\n" + "=" * 50)
    print(col)
    print("=" * 50)
    print("Number of unique careers:", df[col].nunique())
    print("All career labels:", sorted(df[col].unique()))

==================================================
top_career_1
==================================================
Number of unique careers: 46
All career labels: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45)]

==================================================
top_career_2
==================================================
Number of unique careers: 57
All career labels: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56)]

==================================================
top_career_3
==================================================
Number of unique careers: 65
All career labels: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64)]

==================================================
top_career_4
==================================================
Number of unique careers: 70
All career labels: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69)]

==================================================
top_career_5
==================================================
Number of unique careers: 72
All career labels: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71)]

In [50]:
print("\nDATASET SIZE:", len(df))

print("\nCAREER COLUMNS:")
print(career_columns)

print("\nMISSING VALUES:")
print(df[career_columns].isnull().sum())

DATASET SIZE: 2000

CAREER COLUMNS:
['top_career_1', 'top_career_2', 'top_career_3', 'top_career_4', 'top_career_5']

MISSING VALUES:
top_career_1    0
top_career_2    0
top_career_3    0
top_career_4    0
top_career_5    0
dtype: int64

In [51]:
# =========================================================
# FEATURE IMPORTANCE CHECK
# =========================================================

print("INPUT COLUMNS")
print("=" * 50)

for i, col in enumerate(df.columns):
    print(i, col)

INPUT COLUMNS
==================================================
0 field_filter
1 hobby_coding
2 hobby_gaming
3 hobby_reading
4 hobby_writing
5 hobby_music
6 hobby_drawing_art
7 hobby_sports
8 hobby_cooking
9 hobby_photography
10 hobby_travel
11 hobby_science_experiments
12 hobby_volunteering
13 hobby_debating
14 hobby_robotics
15 hobby_fashion
16 hobby_business_trading
17 grade_math
18 grade_science
19 grade_lang
20 grade_social
21 grade_cs
22 score_analytical
23 score_numeric
24 score_verbal
25 score_creative
26 score_social
27 top_career_1
28 top_career_2
29 top_career_3
30 top_career_4
31 top_career_5

In [52]:
print("\nDATA TYPES")
print("=" * 50)

print(df.dtypes)

DATA TYPES
==================================================
field_filter                 object
hobby_coding                  int64
hobby_gaming                  int64
hobby_reading                 int64
hobby_writing                 int64
hobby_music                   int64
hobby_drawing_art             int64
hobby_sports                  int64
hobby_cooking                 int64
hobby_photography             int64
hobby_travel                  int64
hobby_science_experiments     int64
hobby_volunteering            int64
hobby_debating                int64
hobby_robotics                int64
hobby_fashion                 int64
hobby_business_trading        int64
grade_math                    int64
grade_science                 int64
grade_lang                    int64
grade_social                  int64
grade_cs                      int64
score_analytical              int64
score_numeric                 int64
score_verbal                  int64
score_creative                int64
score_social                  int64
top_career_1                  int64
top_career_2                  int64
top_career_3                  int64
top_career_4                  int64
top_career_5                  int64
dtype: object

In [53]:
print("\nSAMPLE DATA")
print("=" * 50)

display(df.head())

SAMPLE DATA
==================================================

,field_filter,hobby_coding,hobby_gaming,hobby_reading,hobby_writing,hobby_music,hobby_drawing_art,hobby_sports,hobby_cooking,hobby_photography,...,score_analytical,score_numeric,score_verbal,score_creative,score_social,top_career_1,top_career_2,top_career_3,top_career_4,top_career_5
0,all,0,0,0,0,0,1,0,0,0,...,96,97,62,78,66,12,16,15,20,65
1,Defense,1,0,0,0,0,0,1,0,0,...,88,65,80,63,77,13,36,7,3,12
2,all,0,0,1,1,0,0,0,0,0,...,74,77,91,81,92,0,8,40,32,51
3,Forensics,0,0,1,0,1,0,0,0,0,...,60,64,56,67,68,11,25,14,28,22
4,all,1,0,1,1,0,1,0,0,0,...,75,57,76,58,65,33,29,6,25,70

In [54]:
# Show the career encoder mapping

for col in career_columns:
    print("\n" + "=" * 50)
    print(col)
    print("=" * 50)

    values = sorted(df[col].dropna().unique())

    print("Number of careers:", len(values))
    print("Career codes:", values)

==================================================
top_career_1
==================================================
Number of careers: 46
Career codes: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45)]

==================================================
top_career_2
==================================================
Number of careers: 57
Career codes: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56)]

==================================================
top_career_3
==================================================
Number of careers: 65
Career codes: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64)]

==================================================
top_career_4
==================================================
Number of careers: 70
Career codes: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69)]

==================================================
top_career_5
==================================================
Number of careers: 72
Career codes: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71)]

In [55]:
for col in career_columns:
    print("\n" + "=" * 50)
    print(col)
    print("=" * 50)

    encoder = label_encoders[col]

    for code, career in enumerate(encoder.classes_):
        print(code, "->", career)

==================================================
top_career_1
==================================================
0 -> Accountant
1 -> Agricultural Scientist
2 -> Aircraft Maintenance Engineer
3 -> Animator
4 -> Architect
5 -> Astronomer
6 -> Biomedical Engineer
7 -> Biomedical Scientist
8 -> Civil Engineer
9 -> College Lecturer
10 -> Cosmetologist
11 -> Criminologist
12 -> Data Analyst
13 -> Defense Scientist
14 -> Dentist
15 -> Doctor
16 -> Fashion Designer
17 -> Financial Analyst
18 -> Food Technologist
19 -> Forensic Scientist
20 -> Graphic Designer
21 -> Hotel Manager
22 -> IT Project Manager
23 -> IT Support Specialist
24 -> Interior Designer
25 -> Investment Banker
26 -> Lawyer / Advocate
27 -> Marine Engineer
28 -> Navy Officer
29 -> Network Engineer
30 -> Physicist
31 -> Pilot
32 -> Policy Analyst
33 -> Public Relations Manager
34 -> Research Scientist
35 -> School Teacher
36 -> Ship Captain
37 -> Social Welfare Officer
38 -> Social Worker
39 -> Software Developer
40 -> Space Scientist
41 -> Sports Coach
42 -> Tourism Manager
43 -> Training Manager
44 -> UI/UX Designer
45 -> Wedding Planner

==================================================
top_career_2
==================================================
0 -> Academic Counselor
1 -> Accountant
2 -> Agricultural Scientist
3 -> Animator
4 -> Army Officer
5 -> Auditor
6 -> Biotechnologist
7 -> Business Analyst
8 -> Chartered Accountant (CA)
9 -> Chemist
10 -> Cloud Engineer
11 -> College Lecturer
12 -> Commercial Pilot
13 -> Criminologist
14 -> Curriculum Developer
15 -> Data Analyst
16 -> Data Scientist
17 -> Dentist
18 -> Doctor
19 -> Environmental Scientist
20 -> Event Manager
21 -> Fashion Designer
22 -> Film Director
23 -> Fitness Trainer
24 -> Food Technologist
25 -> Forensic Scientist
26 -> Graphic Designer
27 -> Hotel Manager
28 -> ISRO Scientist
29 -> IT Project Manager
30 -> IT Support Specialist
31 -> Industrial Designer
32 -> Judge
33 -> Lawyer / Advocate
34 -> Marine Engineer
35 -> Mechanical Engineer
36 -> Navy Officer
37 -> Network Engineer
38 -> Nurse
39 -> Physiotherapist
40 -> Pilot
41 -> Policy Analyst
42 -> Professor
43 -> Public Relations Manager
44 -> Real Estate Manager
45 -> School Teacher
46 -> Ship Captain
47 -> Social Worker
48 -> Software Developer
49 -> Space Scientist
50 -> Technical Consultant
51 -> Textile Designer
52 -> Tourism Manager
53 -> Training Manager
54 -> UI/UX Designer
55 -> Urban Planner
56 -> Web Developer

==================================================
top_career_3
==================================================
0 -> AI Engineer
1 -> Academic Counselor
2 -> Accountant
3 -> Air Force Officer
4 -> Air Traffic Controller
5 -> Airline Manager
6 -> Animator
7 -> Army Officer
8 -> Biomedical Engineer
9 -> Biotechnologist
10 -> Chartered Accountant (CA)
11 -> Cloud Engineer
12 -> College Lecturer
13 -> Commercial Pilot
14 -> Crime Scene Investigator
15 -> Cybersecurity Analyst
16 -> DRDO Scientist
17 -> Data Analyst
18 -> Data Scientist
19 -> Dentist
20 -> Doctor
21 -> Education Consultant
22 -> Electrical Engineer
23 -> Environmental Scientist
24 -> Ethical Hacker
25 -> Event Manager
26 -> Fashion Designer
27 -> Film Director
28 -> Food Technologist
29 -> Graphic Designer
30 -> ISRO Scientist
31 -> IT Support Specialist
32 -> Interior Designer
33 -> Investment Banker
34 -> Judge
35 -> Lawyer / Advocate
36 -> Legal Advisor
37 -> Makeup Artist
38 -> Management Consultant
39 -> Marine Biologist
40 -> Marketing Manager
41 -> Mathematician
42 -> Microbiologist
43 -> Mobile App Developer
44 -> Network Engineer
45 -> Nurse
46 -> Occupational Therapist
47 -> Pharmacist
48 -> Physiotherapist
49 -> Professor
50 -> Real Estate Manager
51 -> Research Analyst
52 -> Risk Analyst
53 -> School Teacher
54 -> Social Worker
55 -> Software Developer
56 -> Special Education Teacher
57 -> Technical Consultant
58 -> Textile Designer
59 -> Tourism Manager
60 -> Training Manager
61 -> UI/UX Designer
62 -> Video Editor
63 -> Web Developer
64 -> Yoga Instructor

==================================================
top_career_4
==================================================
0 -> AI Engineer
1 -> Accountant
2 -> Agricultural Scientist
3 -> Air Force Officer
4 -> Air Traffic Controller
5 -> Aircraft Maintenance Engineer
6 -> Airline Manager
7 -> Architect
8 -> Astronomer
9 -> Banking Officer
10 -> Biotechnologist
11 -> Chartered Accountant (CA)
12 -> Cloud Engineer
13 -> College Lecturer
14 -> Cosmetologist
15 -> Credit Analyst
16 -> Cybersecurity Analyst
17 -> DRDO Scientist
18 -> Data Analyst
19 -> Data Scientist
20 -> Database Administrator
21 -> Defense Scientist
22 -> Education Consultant
23 -> Electronics Engineer
24 -> Ethical Hacker
25 -> Film Director
26 -> Flight Dispatcher
27 -> Food Technologist
28 -> Forensic Psychologist
29 -> Game Developer
30 -> Game Tester
31 -> Geneticist
32 -> Human Resource Manager
33 -> IT Support Specialist
34 -> Industrial Designer
35 -> Interior Designer
36 -> Journalist
37 -> Judge
38 -> Laboratory Researcher
39 -> Legal Advisor
40 -> Librarian
41 -> Machine Learning Engineer
42 -> Makeup Artist
43 -> Marketing Manager
44 -> Medical Lab Technologist
45 -> Microbiologist
46 -> Mobile App Developer
47 -> NGO Program Manager
48 -> Naval Architect
49 -> Network Engineer
50 -> Nurse
51 -> Occupational Therapist
52 -> Pharmacist
53 -> Professor
54 -> Public Prosecutor
55 -> Public Relations Manager
56 -> Radiologist
57 -> Real Estate Manager
58 -> School Teacher
59 -> Social Media Manager
60 -> Social Worker
61 -> Special Education Teacher
62 -> Sports Physiotherapist
63 -> Statistician
64 -> Technical Consultant
65 -> Tourism Manager
66 -> Training Manager
67 -> Video Editor
68 -> Web Developer
69 -> Wedding Planner

==================================================
top_career_5
==================================================
0 -> AI Engineer
1 -> Academic Counselor
2 -> Accountant
3 -> Aerospace Engineer
4 -> Aircraft Maintenance Engineer
5 -> Biomedical Engineer
6 -> Biomedical Scientist
7 -> Biotechnologist
8 -> Chartered Accountant (CA)
9 -> Chemical Engineer
10 -> Civil Services Officer
11 -> Cloud Engineer
12 -> Coast Guard Officer
13 -> College Lecturer
14 -> Content Writer
15 -> Curriculum Developer
16 -> Cybersecurity Analyst
17 -> Data Analyst
18 -> Data Scientist
19 -> Database Administrator
20 -> DevOps Engineer
21 -> Dietitian
22 -> Digital Forensics Analyst
23 -> Digital Marketing Specialist
24 -> Environmental Scientist
25 -> Esports Player
26 -> Ethical Hacker
27 -> Fashion Stylist
28 -> Flight Dispatcher
29 -> Food Technologist
30 -> Game Developer
31 -> Game Tester
32 -> Geneticist
33 -> Geologist
34 -> Graphic Designer
35 -> Human Resource Manager
36 -> IT Support Specialist
37 -> Journalist
38 -> Legal Advisor
39 -> Librarian
40 -> Machine Learning Engineer
41 -> Marine Biologist
42 -> Marketing Manager
43 -> Medical Lab Technologist
44 -> Medical Researcher
45 -> Microbiologist
46 -> Mobile App Developer
47 -> NGO Program Manager
48 -> Network Engineer
49 -> Oceanographer
50 -> Online Course Instructor
51 -> Operations Manager
52 -> Pharmacist
53 -> Physiotherapist
54 -> Professor
55 -> Public Prosecutor
56 -> Radiologist
57 -> Real Estate Manager
58 -> School Teacher
59 -> Scientific Writer
60 -> Social Media Manager
61 -> Social Welfare Officer
62 -> Software Tester / QA Engineer
63 -> Special Education Teacher
64 -> Sports Psychologist
65 -> Systems Analyst
66 -> Technical Consultant
67 -> UI/UX Designer
68 -> Urban Planner
69 -> VFX Artist
70 -> Video Editor
71 -> Wedding Planner

In [56]:
print(df[career_columns].head(20))

    top_career_1  top_career_2  top_career_3  top_career_4  top_career_5
0             12            16            15            20            65
1             13            36             7             3            12
2              0             8            40            32            51
3             11            25            14            28            22
4             33            29             6            25            70
5             37            33            34            39            55
6             33            29            60             1             8
7             17             7            52            15            17
8              2            40            13             4            28
9             37            33            34            39            55
10             2            40            13             4            28
11            20            21            32            59            69
12            38            45            49            61            61
13            35            42            56            66            13
14            28             4             3            21            12
15             0             8            40            32            51
16            10            21            58            42            27
17            18             6            42            31            41
18            34            16            51            38            59
19            40            28            16             8             3

In [57]:
# =========================================================
# STEP 4 - CREATE CAREER-RELEVANT FEATURES
# =========================================================

df_model = df.copy()

# ---------------------------------------------------------
# Technical / Engineering Strength
# ---------------------------------------------------------

df_model["technical_strength"] = (
    df_model["grade_math"] +
    df_model["grade_science"] +
    df_model["grade_cs"] +
    df_model["score_analytical"] +
    df_model["score_numeric"]
) / 5


# ---------------------------------------------------------
# Communication Strength
# ---------------------------------------------------------

df_model["communication_strength"] = (
    df_model["grade_lang"] +
    df_model["grade_social"] +
    df_model["score_verbal"] +
    df_model["score_social"]
) / 4


# ---------------------------------------------------------
# Creative Strength
# ---------------------------------------------------------

df_model["creative_strength"] = (
    df_model["score_creative"] +
    df_model["hobby_drawing_art"] * 100 +
    df_model["hobby_writing"] * 100 +
    df_model["hobby_music"] * 100 +
    df_model["hobby_photography"] * 100 +
    df_model["hobby_fashion"] * 100
) / 6


# ---------------------------------------------------------
# Business Strength
# ---------------------------------------------------------

df_model["business_strength"] = (
    df_model["score_numeric"] +
    df_model["score_social"] +
    df_model["score_verbal"] +
    df_model["hobby_business_trading"] * 100 +
    df_model["hobby_debating"] * 100
) / 5


# ---------------------------------------------------------
# Science Strength
# ---------------------------------------------------------

df_model["science_strength"] = (
    df_model["grade_science"] +
    df_model["grade_math"] +
    df_model["score_analytical"] +
    df_model["hobby_science_experiments"] * 100 +
    df_model["hobby_robotics"] * 100
) / 5


# ---------------------------------------------------------
# Social / People Strength
# ---------------------------------------------------------

df_model["social_strength"] = (
    df_model["score_social"] +
    df_model["score_verbal"] +
    df_model["grade_social"] +
    df_model["hobby_volunteering"] * 100 +
    df_model["hobby_debating"] * 100
) / 5


print("New feature engineering completed!")
print("\nNew columns:")

new_features = [
    "technical_strength",
    "communication_strength",
    "creative_strength",
    "business_strength",
    "science_strength",
    "social_strength"
]

print(new_features)

print("\nNew dataset shape:", df_model.shape)

New feature engineering completed!

New columns:
['technical_strength', 'communication_strength', 'creative_strength', 'business_strength', 'science_strength', 'social_strength']

New dataset shape: (2000, 38)

In [58]:
# =========================================================
# STEP 5 - PREPARE FEATURES AND TARGETS
# =========================================================

# Input features
feature_columns = [
    "field_filter",

    # Hobbies
    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading",

    # Grades
    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs",

    # Aptitude
    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social",

    # New engineered features
    "technical_strength",
    "communication_strength",
    "creative_strength",
    "business_strength",
    "science_strength",
    "social_strength"
]

# Target columns
target_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]

# Create X and y
X = df_model[feature_columns].copy()
y = df_model[target_columns].copy()

print("Training data prepared!")
print("=" * 50)
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nNumber of input features:", len(feature_columns))
print("Number of target columns:", len(target_columns))

print("\nInput features:")
print(feature_columns)

Training data prepared!
==================================================
X shape: (2000, 33)
y shape: (2000, 5)

Number of input features: 33
Number of target columns: 5

Input features:
['field_filter', 'hobby_coding', 'hobby_gaming', 'hobby_reading', 'hobby_writing', 'hobby_music', 'hobby_drawing_art', 'hobby_sports', 'hobby_cooking', 'hobby_photography', 'hobby_travel', 'hobby_science_experiments', 'hobby_volunteering', 'hobby_debating', 'hobby_robotics', 'hobby_fashion', 'hobby_business_trading', 'grade_math', 'grade_science', 'grade_lang', 'grade_social', 'grade_cs', 'score_analytical', 'score_numeric', 'score_verbal', 'score_creative', 'score_social', 'technical_strength', 'communication_strength', 'creative_strength', 'business_strength', 'science_strength', 'social_strength']

In [59]:
# =========================================================
# STEP 6 - ENCODE CAREER TARGETS
# =========================================================

from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in target_columns:

    encoder = LabelEncoder()

    y[col] = encoder.fit_transform(y[col].astype(str))

    label_encoders[col] = encoder

    print(f"\n{col}")
    print("Number of careers:", len(encoder.classes_))
    print("Example mapping:")

    for i, career in enumerate(encoder.classes_[:10]):
        print(i, "->", career)

top_career_1
Number of careers: 46
Example mapping:
0 -> 0
1 -> 1
2 -> 10
3 -> 11
4 -> 12
5 -> 13
6 -> 14
7 -> 15
8 -> 16
9 -> 17

top_career_2
Number of careers: 57
Example mapping:
0 -> 0
1 -> 1
2 -> 10
3 -> 11
4 -> 12
5 -> 13
6 -> 14
7 -> 15
8 -> 16
9 -> 17

top_career_3
Number of careers: 65
Example mapping:
0 -> 0
1 -> 1
2 -> 10
3 -> 11
4 -> 12
5 -> 13
6 -> 14
7 -> 15
8 -> 16
9 -> 17

top_career_4
Number of careers: 70
Example mapping:
0 -> 0
1 -> 1
2 -> 10
3 -> 11
4 -> 12
5 -> 13
6 -> 14
7 -> 15
8 -> 16
9 -> 17

top_career_5
Number of careers: 72
Example mapping:
0 -> 0
1 -> 1
2 -> 10
3 -> 11
4 -> 12
5 -> 13
6 -> 14
7 -> 15
8 -> 16
9 -> 17

In [60]:
# =========================================================
# STEP 7 - TRAIN / TEST SPLIT
# =========================================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Data split completed!")
print("=" * 50)

print("Training samples:", len(X_train))
print("Testing samples :", len(X_test))

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

Data split completed!
==================================================
Training samples: 1600
Testing samples : 400
X_train: (1600, 33)
X_test : (400, 33)
y_train: (1600, 5)
y_test : (400, 5)

In [61]:
# =========================================================
# STEP 8 - PREPROCESS FEATURES
# =========================================================

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

# Categorical column
categorical_features = ["field_filter"]

# Numerical columns
numerical_features = [
    col for col in feature_columns
    if col not in categorical_features
]

# Numerical preprocessing
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

# Complete preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        ),
        (
            "numerical",
            numeric_pipeline,
            numerical_features
        )
    ]
)

# Fit only on training data
X_train_processed = preprocessor.fit_transform(X_train)

# Transform test data
X_test_processed = preprocessor.transform(X_test)

print("Preprocessing completed!")
print("=" * 50)

print("Original training shape:", X_train.shape)
print("Processed training shape:", X_train_processed.shape)

print("Original testing shape:", X_test.shape)
print("Processed testing shape:", X_test_processed.shape)

Preprocessing completed!
==================================================
Original training shape: (1600, 33)
Processed training shape: (1600, 52)
Original testing shape: (400, 33)
Processed testing shape: (400, 52)

In [62]:
# =========================================================
# STEP 9 - TRAIN RANDOM FOREST MODEL
# =========================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier

rf_base = RandomForestClassifier(
    n_estimators=500,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model = MultiOutputClassifier(
    rf_base,
    n_jobs=-1
)

print("Training Random Forest...")
print("Please wait...")

rf_model.fit(
    X_train_processed,
    y_train
)

print("✅ Random Forest training completed!")

Training Random Forest...
Please wait...
✅ Random Forest training completed!

In [63]:
# =========================================================
# STEP 10 - EVALUATE RANDOM FOREST
# =========================================================

from sklearn.metrics import accuracy_score

rf_predictions = rf_model.predict(X_test_processed)

print("=" * 50)
print("RANDOM FOREST CAREER ACCURACY")
print("=" * 50)

accuracies = []

for i, col in enumerate(target_columns):

    accuracy = accuracy_score(
        y_test[col],
        rf_predictions[:, i]
    )

    accuracies.append(accuracy)

    print(f"{col}: {accuracy * 100:.2f}%")

average_accuracy = sum(accuracies) / len(accuracies)

print("=" * 50)
print(f"Average Accuracy: {average_accuracy * 100:.2f}%")
print("=" * 50)

/usr/local/lib/python3.13/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

==================================================
RANDOM FOREST CAREER ACCURACY
==================================================
top_career_1: 76.00%
top_career_2: 70.00%
top_career_3: 71.50%
top_career_4: 68.25%
top_career_5: 69.00%
==================================================
Average Accuracy: 70.95%
==================================================

In [64]:
# =========================================================
# STEP 11 - CHECK CAREER / FIELD RELATIONSHIP
# =========================================================

print("=" * 60)
print("CAREER DISTRIBUTION BY FIELD")
print("=" * 60)

for career_col in target_columns:

    print("\n" + "-" * 60)
    print(career_col)

    table = pd.crosstab(
        df["field_filter"],
        df[career_col],
        normalize="index"
    )

    display(table.round(2))

============================================================
CAREER DISTRIBUTION BY FIELD
============================================================

------------------------------------------------------------
top_career_1

top_career_1,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,45
field_filter,,,,,,,,,,,,,,,,,,,,,
Aviation,0.00,0.00,0.75,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Biotech,0.00,0.09,0.00,0.00,0.00,0.00,0.42,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.32,0.00,0.00,0.00
Business & Finance,0.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Defense,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Design,0.00,0.00,0.00,0.00,0.67,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Education,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.03,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.43,0.00,0.00
Engineering,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Fashion,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Forensics,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Healthcare,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.0,0.00,...,0.00,0.00,0.13,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Hospitality,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.23
IT & Computer,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.42,0.00,0.0,0.00,0.00,0.00,0.00
Law & Government,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.89,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Marine,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.37,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Media & Creative,0.00,0.00,0.00,0.17,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Research,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Space Science,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.99,0.0,0.00,0.00,0.00,0.00
Sports / Fitness,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.00,0.00,0.00,1.0,0.00,0.00,0.00,0.00
all,0.10,0.00,0.00,0.07,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.04,0.10,0.00,0.0,0.00,0.00,0.02,0.00

------------------------------------------------------------
top_career_2

top_career_2,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
field_filter,,,,,,,,,,,,,,,,,,,,,
Aviation,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Biotech,0.00,0.00,0.15,0.00,0.00,0.00,0.17,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.17,0.00,0.0,0.00,0.00
Business & Finance,0.00,0.00,0.00,0.00,0.00,0.11,0.00,0.01,0.88,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Defense,0.00,0.00,0.00,0.00,0.73,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Design,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.67,0.00
Education,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Engineering,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Fashion,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.64,0.00,0.00,0.0,0.00,0.00
Forensics,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Healthcare,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Hospitality,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
IT & Computer,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.06,0.00,0.02,0.00,0.00,0.00,0.0,0.00,0.42
Law & Government,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Marine,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Media & Creative,0.00,0.00,0.00,0.27,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Research,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Space Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.0,0.00,0.00
Sports / Fitness,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
all,0.00,0.04,0.00,0.05,0.00,0.02,0.00,0.01,0.10,0.0,...,0.01,0.02,0.00,0.04,0.00,0.00,0.05,0.0,0.00,0.10

------------------------------------------------------------
top_career_3

top_career_3,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
field_filter,,,,,,,,,,,,,,,,,,,,,
Aviation,0.00,0.00,0.00,0.00,0.25,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Biotech,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.34,0.09,...,0.0,0.00,0.00,0.00,0.02,0.00,0.0,0.00,0.00,0.0
Business & Finance,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Defense,0.00,0.00,0.00,0.73,0.00,0.00,0.00,0.27,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Design,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Education,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.54,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Engineering,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Fashion,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.36,0.00,0.00,0.0,0.00,0.00,0.0
Forensics,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Healthcare,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Hospitality,0.00,0.00,0.00,0.00,0.00,0.77,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
IT & Computer,0.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.06,0.0
Law & Government,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Marine,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Media & Creative,0.00,0.00,0.00,0.00,0.00,0.00,0.20,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.17,0.00,0.0
Research,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Space Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0
Sports / Fitness,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,1.0
all,0.12,0.00,0.05,0.00,0.00,0.00,0.01,0.00,0.00,0.00,...,0.0,0.00,0.02,0.00,0.00,0.07,0.0,0.07,0.02,0.0

------------------------------------------------------------
top_career_4

top_career_4,0,1,2,3,4,5,6,7,8,9,...,60,61,62,63,64,65,66,67,68,69
field_filter,,,,,,,,,,,,,,,,,,,,,
Aviation,0.00,0.00,0.00,0.00,0.75,0.02,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Biotech,0.00,0.00,0.25,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.05,0.00,0.00,0.0,0.00
Business & Finance,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.11,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Defense,0.00,0.00,0.00,0.27,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Design,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.33,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Education,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.36,0.0,0.0,0.00,0.00,0.45,0.00,0.0,0.00
Engineering,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Fashion,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Forensics,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Healthcare,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Hospitality,0.00,0.00,0.00,0.00,0.00,0.00,0.23,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.69
IT & Computer,0.12,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Law & Government,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Marine,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Media & Creative,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.27,0.0,0.00
Research,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,1.0,0.00,0.00,0.00,0.00,0.0,0.00
Space Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.99,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
Sports / Fitness,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,1.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00
all,0.04,0.07,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,...,0.0,0.04,0.0,0.0,0.01,0.00,0.00,0.05,0.0,0.00

------------------------------------------------------------
top_career_5

top_career_5,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
field_filter,,,,,,,,,,,,,,,,,,,,,
Aviation,0.00,0.00,0.00,0.0,0.23,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Biotech,0.00,0.00,0.00,0.0,0.00,0.02,0.00,0.29,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Business & Finance,0.00,0.00,0.01,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Defense,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Design,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.33,0.00,0.00,0.00
Education,0.00,0.09,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.06,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Engineering,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,1.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Fashion,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Forensics,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Healthcare,0.00,0.00,0.00,0.0,0.00,0.00,0.02,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Hospitality,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.08
IT & Computer,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.20,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Law & Government,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Marine,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Media & Creative,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.33,0.20,0.00
Research,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Science,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Space Science,0.00,0.00,0.00,1.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Sports / Fitness,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,...,0.00,0.00,1.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00
all,0.01,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.07,0.0,...,0.06,0.01,0.0,0.03,0.0,0.0,0.00,0.05,0.01,0.00

In [65]:
# =========================================================
# STEP 11B - CHECK CAREER / SCORE RELATIONSHIP
# =========================================================

score_columns = [
    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"
]

for career_col in target_columns:

    print("\n" + "=" * 60)
    print(career_col)
    print("=" * 60)

    result = df.groupby(career_col)[score_columns].mean()

    display(result.round(1))

============================================================
top_career_1
============================================================

,score_analytical,score_numeric,score_verbal,score_creative,score_social
top_career_1,,,,,
0,70.2,73.1,74.3,58.2,74.3
1,83.2,85.0,62.5,59.0,46.7
2,75.0,78.5,69.9,53.3,64.7
3,60.0,57.0,63.9,72.4,64.7
4,64.8,58.4,63.9,83.9,63.4
5,74.0,75.0,53.0,86.0,58.0
6,76.6,72.6,56.8,68.9,56.0
7,79.0,85.5,51.0,40.5,70.5
8,77.5,84.4,55.5,63.0,53.0
9,39.0,75.0,54.5,72.0,78.0
10,58.0,59.3,69.7,81.6,70.0
11,69.8,61.6,64.1,62.4,65.0
12,87.6,89.9,68.1,60.2,46.7
13,78.1,82.2,67.9,54.9,71.7
14,59.7,58.7,51.8,60.5,73.5
15,71.4,65.5,70.7,51.9,81.6
16,52.4,48.6,72.2,89.4,73.0
17,86.3,87.1,66.6,66.9,44.2
18,71.9,55.8,59.2,68.2,54.7
19,80.6,76.0,67.4,55.6,61.7
20,50.8,43.4,70.3,89.0,68.6
21,58.3,64.5,79.8,64.8,80.4
22,72.1,76.3,74.1,61.9,72.3
23,56.6,57.6,59.9,66.9,68.8
24,47.0,43.0,65.8,88.6,68.1
25,60.0,57.9,59.7,65.3,64.1
26,75.8,55.3,66.0,53.3,65.5
27,73.8,77.8,65.0,59.7,62.0
28,65.9,67.0,61.8,59.9,71.0
29,77.6,82.5,54.3,65.8,53.4
30,82.3,87.3,59.4,66.2,54.3
31,60.4,68.9,71.3,57.5,67.9
32,95.0,81.0,74.0,47.0,62.0
33,71.2,70.9,74.0,69.0,71.2
34,84.0,80.4,70.2,72.6,56.3
35,65.5,52.8,78.1,64.5,83.4
36,61.7,63.5,64.3,55.5,63.3
37,72.3,59.8,82.8,56.8,72.4
38,65.7,45.3,78.2,67.6,81.2
39,83.0,69.2,59.8,68.1,48.0
40,86.1,87.0,63.5,69.2,56.1
41,58.5,60.0,66.7,62.5,78.9
42,75.8,74.8,70.1,67.3,67.2
43,70.1,71.8,78.7,66.1,78.2
44,56.2,44.4,67.5,92.1,71.5
45,45.8,45.8,71.5,66.4,80.9

============================================================
top_career_2
============================================================

,score_analytical,score_numeric,score_verbal,score_creative,score_social
top_career_2,,,,,
0,39.0,75.0,54.5,72.0,78.0
1,69.7,78.6,76.6,63.3,74.2
2,79.5,72.0,59.7,63.3,46.1
3,64.3,61.9,71.0,76.2,70.4
4,65.9,67.0,61.8,59.9,71.0
5,60.0,57.9,59.7,65.3,64.1
6,71.9,55.8,59.2,68.2,54.7
7,86.3,87.1,66.6,66.9,44.2
8,70.2,73.1,74.3,58.2,74.3
9,82.3,87.3,59.4,66.2,54.3
10,77.6,82.5,54.3,65.8,53.4
11,55.0,79.0,75.0,72.0,55.0
12,60.4,68.9,71.3,57.5,67.9
13,80.6,76.0,67.4,55.6,61.7
14,86.0,72.0,69.5,79.5,74.5
15,82.6,83.4,68.1,45.6,68.9
16,85.1,83.3,69.5,68.8,53.4
17,66.5,63.5,60.5,60.0,79.5
18,72.9,61.0,73.4,55.7,80.4
19,83.2,85.0,62.5,59.0,46.7
20,58.3,64.5,79.8,64.8,80.4
21,51.4,46.1,70.5,86.8,69.5
22,60.0,57.0,63.9,72.4,64.7
23,58.5,60.0,66.7,62.5,78.9
24,70.8,68.0,53.3,78.5,54.0
25,69.8,61.6,64.1,62.4,65.0
26,66.3,53.7,78.2,91.6,68.2
27,45.8,45.8,71.5,66.4,80.9
28,86.1,87.0,63.5,69.2,56.1
29,72.2,77.4,75.2,63.4,73.1
30,57.4,59.5,65.3,79.8,71.9
31,47.0,43.0,65.8,88.6,68.1
32,75.8,55.3,66.0,53.3,65.5
33,72.5,57.3,82.8,55.5,72.6
34,61.7,63.5,64.3,55.5,63.3
35,77.5,84.4,55.5,63.0,53.0
36,78.1,82.2,67.9,54.9,71.7
37,77.5,83.6,69.1,63.8,62.7
38,71.7,65.2,70.9,51.9,81.5
39,59.7,58.7,51.8,60.5,73.5
40,75.0,78.5,69.9,53.3,64.7
41,73.8,83.8,81.5,65.5,69.0
42,65.5,52.8,78.1,64.5,83.4
43,67.7,72.3,77.6,61.0,77.3
44,75.8,74.8,70.1,67.3,67.2
45,66.6,56.7,79.7,66.8,80.2
46,73.8,77.8,65.0,59.7,62.0
47,52.5,56.8,84.2,65.2,75.0
48,82.6,69.7,70.8,72.7,67.0
49,74.0,75.0,53.0,86.0,58.0
50,56.2,57.6,59.9,66.5,68.2
51,52.4,48.6,72.2,89.4,73.0
52,77.0,75.5,56.1,68.6,66.2
53,72.1,78.9,72.4,63.1,72.3
54,52.5,59.5,80.5,93.0,87.0
55,64.8,58.4,63.9,83.9,63.4
56,83.0,69.2,59.8,68.1,48.0

============================================================
top_career_3
============================================================

,score_analytical,score_numeric,score_verbal,score_creative,score_social
top_career_3,,,,,
0,77.6,82.5,54.3,65.8,53.4
1,55.0,79.0,75.0,72.0,55.0
2,72.1,78.9,72.4,63.1,72.3
3,65.9,67.0,61.8,59.9,71.0
4,60.4,68.9,71.3,57.5,67.9
...,...,...,...,...,...
60,72.8,79.0,77.0,63.3,72.7
61,47.0,75.0,88.0,95.0,78.0
62,60.0,57.0,63.9,72.4,64.7
63,82.6,69.7,70.8,72.7,67.0
64,58.5,60.0,66.7,62.5,78.9

============================================================
top_career_4
============================================================

,score_analytical,score_numeric,score_verbal,score_creative,score_social
top_career_4,,,,,
0,77.5,83.6,69.1,63.8,62.7
1,72.8,79.0,77.0,63.3,72.7
2,81.2,77.7,68.1,63.4,68.1
3,78.1,82.2,67.9,54.9,71.7
4,75.0,78.5,69.9,53.3,64.7
...,...,...,...,...,...
65,84.0,80.0,68.3,61.3,53.7
66,66.1,54.0,79.9,64.4,84.0
67,64.3,61.9,71.0,76.2,70.4
68,68.5,70.5,78.5,69.5,70.5
69,56.7,63.8,80.2,64.4,80.4

============================================================
top_career_5
============================================================

,score_analytical,score_numeric,score_verbal,score_creative,score_social
top_career_5,,,,,
0,74.8,79.5,77.0,69.0,70.5
1,62.3,46.8,69.0,65.2,80.3
2,90.2,86.0,68.0,58.2,50.5
3,85.9,86.8,63.4,69.4,56.2
4,57.9,69.8,70.8,57.8,68.0
...,...,...,...,...,...
67,77.0,55.0,77.0,97.0,74.0
68,47.0,43.0,65.8,88.6,68.1
69,48.2,40.9,70.3,88.6,69.6
70,69.1,64.9,78.8,85.2,66.6
71,72.2,70.8,76.6,68.2,79.8

In [66]:
# =========================================================
# STEP 12 - CHECK REMAINING BLANK CAREER VALUES
# =========================================================

print("=" * 50)
print("REMAINING BLANK VALUES")
print("=" * 50)

for col in target_columns:
    blanks = df[col].isna().sum()
    empty = (df[col].astype(str).str.strip() == "").sum()


    print(f"{col}: {blanks + empty}")

==================================================
REMAINING BLANK VALUES
==================================================
top_career_1: 0
top_career_2: 0
top_career_3: 0
top_career_4: 0
top_career_5: 0

In [67]:
# =========================================================
# STEP 12B - CHECK UNIQUE CAREER COUNTS
# =========================================================

print("=" * 50)
print("UNIQUE CAREERS")
print("=" * 50)

for col in target_columns:
    print(
        f"{col}:",
        df[col].nunique(),
        "unique careers"
    )

==================================================
UNIQUE CAREERS
==================================================
top_career_1: 46 unique careers
top_career_2: 57 unique careers
top_career_3: 65 unique careers
top_career_4: 70 unique careers
top_career_5: 72 unique careers

In [68]:
# =========================================================
# STEP 13 - LIST ALL CAREERS
# =========================================================

all_careers = set()

for col in target_columns:
    all_careers.update(
        df[col].dropna().astype(str).str.strip().unique()
    )

all_careers = sorted(all_careers)

print("=" * 60)
print("ALL UNIQUE CAREERS")
print("=" * 60)

for i, career in enumerate(all_careers):
    print(f"{i}: {career}")

print("\nTotal unique careers:", len(all_careers))

============================================================
ALL UNIQUE CAREERS
============================================================
0: 0
1: 1
2: 10
3: 11
4: 12
5: 13
6: 14
7: 15
8: 16
9: 17
10: 18
11: 19
12: 2
13: 20
14: 21
15: 22
16: 23
17: 24
18: 25
19: 26
20: 27
21: 28
22: 29
23: 3
24: 30
25: 31
26: 32
27: 33
28: 34
29: 35
30: 36
31: 37
32: 38
33: 39
34: 4
35: 40
36: 41
37: 42
38: 43
39: 44
40: 45
41: 46
42: 47
43: 48
44: 49
45: 5
46: 50
47: 51
48: 52
49: 53
50: 54
51: 55
52: 56
53: 57
54: 58
55: 59
56: 6
57: 60
58: 61
59: 62
60: 63
61: 64
62: 65
63: 66
64: 67
65: 68
66: 69
67: 7
68: 70
69: 71
70: 8
71: 9

Total unique careers: 72

In [69]:
# =========================================================
# STEP 13B - TOTAL CAREER FREQUENCY
# =========================================================

career_counts = {}

for col in target_columns:

    for career in df[col].dropna().astype(str).str.strip():

        if career not in career_counts:
            career_counts[career] = 0

        career_counts[career] += 1

career_frequency = (
    pd.Series(career_counts)
    .sort_values(ascending=False)
)

print("=" * 60)
print("CAREER FREQUENCY")
print("=" * 60)

display(career_frequency.to_frame("count"))

============================================================
CAREER FREQUENCY
============================================================

    count
8     342
22    341
0     305
40    289
33    273
..    ...
70     18
57     16
17     15
54     14
71      5

[72 rows x 1 columns]

In [70]:
# =========================================================
# STEP 14 - CAREER ID MAPPING
# =========================================================

print("=" * 60)
print("CAREER ID → CAREER NAME")
print("=" * 60)

career_mapping = {}

for col in target_columns:

    for value in df[col].dropna().unique():

        try:
            career_id = int(value)

            if career_id not in career_mapping:
                career_mapping[career_id] = set()

            career_mapping[career_id].add(col)

        except:
            pass


for career_id in sorted(career_mapping):

    print(
        f"{career_id:2d} -> appears in: "
        f"{', '.join(sorted(career_mapping[career_id]))}"
    )

============================================================
CAREER ID → CAREER NAME
============================================================
 0 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 1 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 2 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 3 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 4 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 5 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 6 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 7 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 8 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
 9 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
10 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
11 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
12 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
13 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
14 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
15 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
16 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
17 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
18 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
19 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
20 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
21 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
22 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
23 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
24 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
25 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
26 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
27 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
28 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
29 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
30 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
31 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
32 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
33 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
34 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
35 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
36 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
37 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
38 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
39 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
40 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
41 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
42 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
43 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
44 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
45 -> appears in: top_career_1, top_career_2, top_career_3, top_career_4, top_career_5
46 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
47 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
48 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
49 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
50 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
51 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
52 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
53 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
54 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
55 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
56 -> appears in: top_career_2, top_career_3, top_career_4, top_career_5
57 -> appears in: top_career_3, top_career_4, top_career_5
58 -> appears in: top_career_3, top_career_4, top_career_5
59 -> appears in: top_career_3, top_career_4, top_career_5
60 -> appears in: top_career_3, top_career_4, top_career_5
61 -> appears in: top_career_3, top_career_4, top_career_5
62 -> appears in: top_career_3, top_career_4, top_career_5
63 -> appears in: top_career_3, top_career_4, top_career_5
64 -> appears in: top_career_3, top_career_4, top_career_5
65 -> appears in: top_career_4, top_career_5
66 -> appears in: top_career_4, top_career_5
67 -> appears in: top_career_4, top_career_5
68 -> appears in: top_career_4, top_career_5
69 -> appears in: top_career_4, top_career_5
70 -> appears in: top_career_5
71 -> appears in: top_career_5

In [71]:
# =========================================================
# STEP 14B - SAFELY CHECK CAREER VARIABLES
# =========================================================

career_variables = [
    name for name in list(globals().keys())
    if "career" in name.lower()
]

print("Variables containing 'career':")
print("=" * 50)

for name in career_variables:
    print(name, "->", type(globals()[name]))

Variables containing 'career':
==================================================
career_columns -> <class 'list'>
all_careers -> <class 'list'>
career -> <class 'str'>
career_col -> <class 'str'>
career_counts -> <class 'dict'>
career_frequency -> <class 'pandas.core.series.Series'>
career_mapping -> <class 'dict'>
career_id -> <class 'int'>

In [72]:
# =========================================================
# STEP 15 - CHECK LABEL ENCODER CAREER NAMES
# =========================================================

print("=" * 60)
print("CAREER LABEL ENCODER MAPPINGS")
print("=" * 60)

for col in target_columns:

    print("\n" + "-" * 60)
    print(col)

    encoder = label_encoders[col]

    print("Number of classes:", len(encoder.classes_))

    for i, name in enumerate(encoder.classes_):
        print(f"{i:2d} -> {name}")

============================================================
CAREER LABEL ENCODER MAPPINGS
============================================================

------------------------------------------------------------
top_career_1
Number of classes: 46
 0 -> 0
 1 -> 1
 2 -> 10
 3 -> 11
 4 -> 12
 5 -> 13
 6 -> 14
 7 -> 15
 8 -> 16
 9 -> 17
10 -> 18
11 -> 19
12 -> 2
13 -> 20
14 -> 21
15 -> 22
16 -> 23
17 -> 24
18 -> 25
19 -> 26
20 -> 27
21 -> 28
22 -> 29
23 -> 3
24 -> 30
25 -> 31
26 -> 32
27 -> 33
28 -> 34
29 -> 35
30 -> 36
31 -> 37
32 -> 38
33 -> 39
34 -> 4
35 -> 40
36 -> 41
37 -> 42
38 -> 43
39 -> 44
40 -> 45
41 -> 5
42 -> 6
43 -> 7
44 -> 8
45 -> 9

------------------------------------------------------------
top_career_2
Number of classes: 57
 0 -> 0
 1 -> 1
 2 -> 10
 3 -> 11
 4 -> 12
 5 -> 13
 6 -> 14
 7 -> 15
 8 -> 16
 9 -> 17
10 -> 18
11 -> 19
12 -> 2
13 -> 20
14 -> 21
15 -> 22
16 -> 23
17 -> 24
18 -> 25
19 -> 26
20 -> 27
21 -> 28
22 -> 29
23 -> 3
24 -> 30
25 -> 31
26 -> 32
27 -> 33
28 -> 34
29 -> 35
30 -> 36
31 -> 37
32 -> 38
33 -> 39
34 -> 4
35 -> 40
36 -> 41
37 -> 42
38 -> 43
39 -> 44
40 -> 45
41 -> 46
42 -> 47
43 -> 48
44 -> 49
45 -> 5
46 -> 50
47 -> 51
48 -> 52
49 -> 53
50 -> 54
51 -> 55
52 -> 56
53 -> 6
54 -> 7
55 -> 8
56 -> 9

------------------------------------------------------------
top_career_3
Number of classes: 65
 0 -> 0
 1 -> 1
 2 -> 10
 3 -> 11
 4 -> 12
 5 -> 13
 6 -> 14
 7 -> 15
 8 -> 16
 9 -> 17
10 -> 18
11 -> 19
12 -> 2
13 -> 20
14 -> 21
15 -> 22
16 -> 23
17 -> 24
18 -> 25
19 -> 26
20 -> 27
21 -> 28
22 -> 29
23 -> 3
24 -> 30
25 -> 31
26 -> 32
27 -> 33
28 -> 34
29 -> 35
30 -> 36
31 -> 37
32 -> 38
33 -> 39
34 -> 4
35 -> 40
36 -> 41
37 -> 42
38 -> 43
39 -> 44
40 -> 45
41 -> 46
42 -> 47
43 -> 48
44 -> 49
45 -> 5
46 -> 50
47 -> 51
48 -> 52
49 -> 53
50 -> 54
51 -> 55
52 -> 56
53 -> 57
54 -> 58
55 -> 59
56 -> 6
57 -> 60
58 -> 61
59 -> 62
60 -> 63
61 -> 64
62 -> 7
63 -> 8
64 -> 9

------------------------------------------------------------
top_career_4
Number of classes: 70
 0 -> 0
 1 -> 1
 2 -> 10
 3 -> 11
 4 -> 12
 5 -> 13
 6 -> 14
 7 -> 15
 8 -> 16
 9 -> 17
10 -> 18
11 -> 19
12 -> 2
13 -> 20
14 -> 21
15 -> 22
16 -> 23
17 -> 24
18 -> 25
19 -> 26
20 -> 27
21 -> 28
22 -> 29
23 -> 3
24 -> 30
25 -> 31
26 -> 32
27 -> 33
28 -> 34
29 -> 35
30 -> 36
31 -> 37
32 -> 38
33 -> 39
34 -> 4
35 -> 40
36 -> 41
37 -> 42
38 -> 43
39 -> 44
40 -> 45
41 -> 46
42 -> 47
43 -> 48
44 -> 49
45 -> 5
46 -> 50
47 -> 51
48 -> 52
49 -> 53
50 -> 54
51 -> 55
52 -> 56
53 -> 57
54 -> 58
55 -> 59
56 -> 6
57 -> 60
58 -> 61
59 -> 62
60 -> 63
61 -> 64
62 -> 65
63 -> 66
64 -> 67
65 -> 68
66 -> 69
67 -> 7
68 -> 8
69 -> 9

------------------------------------------------------------
top_career_5
Number of classes: 72
 0 -> 0
 1 -> 1
 2 -> 10
 3 -> 11
 4 -> 12
 5 -> 13
 6 -> 14
 7 -> 15
 8 -> 16
 9 -> 17
10 -> 18
11 -> 19
12 -> 2
13 -> 20
14 -> 21
15 -> 22
16 -> 23
17 -> 24
18 -> 25
19 -> 26
20 -> 27
21 -> 28
22 -> 29
23 -> 3
24 -> 30
25 -> 31
26 -> 32
27 -> 33
28 -> 34
29 -> 35
30 -> 36
31 -> 37
32 -> 38
33 -> 39
34 -> 4
35 -> 40
36 -> 41
37 -> 42
38 -> 43
39 -> 44
40 -> 45
41 -> 46
42 -> 47
43 -> 48
44 -> 49
45 -> 5
46 -> 50
47 -> 51
48 -> 52
49 -> 53
50 -> 54
51 -> 55
52 -> 56
53 -> 57
54 -> 58
55 -> 59
56 -> 6
57 -> 60
58 -> 61
59 -> 62
60 -> 63
61 -> 64
62 -> 65
63 -> 66
64 -> 67
65 -> 68
66 -> 69
67 -> 7
68 -> 70
69 -> 71
70 -> 8
71 -> 9

In [73]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np


# =========================================================
# FEATURES
# =========================================================

feature_columns = [
    "field_filter",

    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading",

    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs",

    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"
]


# =========================================================
# INPUT DATA
# =========================================================

X = df[feature_columns].copy()

X["field_filter"] = X["field_filter"].astype(str)


# =========================================================
# ENCODE FIELD
# =========================================================

field_encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

X_field = field_encoder.fit_transform(
    X[["field_filter"]]
)

X_numeric = X.drop(
    columns=["field_filter"]
).values

X_processed = np.hstack([
    X_field,
    X_numeric
])


# =========================================================
# CAREER COLUMNS
# =========================================================

career_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]


# =========================================================
# TRAIN 5 SEPARATE MODELS
# =========================================================

career_models = {}
career_predictions = {}

accuracies = []


for target_col in career_columns:

    print("=" * 60)
    print(target_col)
    print("=" * 60)

    y = df[target_col]

    # Remove missing values
    valid = y.notna()

    X_target = X_processed[valid]
    y_target = y[valid]


    # -----------------------------------------------------
    # TRAIN / TEST SPLIT
    # -----------------------------------------------------

    # IMPORTANT:
    # No stratify because some careers occur only once.

    X_train, X_test, y_train, y_test = train_test_split(
        X_target,
        y_target,
        test_size=0.20,
        random_state=42
    )


    # -----------------------------------------------------
    # MODEL
    # -----------------------------------------------------

    model = HistGradientBoostingClassifier(
        max_iter=300,
        learning_rate=0.08,
        max_leaf_nodes=31,
        l2_regularization=1.0,
        random_state=42
    )


    # -----------------------------------------------------
    # TRAIN
    # -----------------------------------------------------

    model.fit(
        X_train,
        y_train
    )


    # -----------------------------------------------------
    # PREDICT
    # -----------------------------------------------------

    pred = model.predict(X_test)


    # -----------------------------------------------------
    # ACCURACY
    # -----------------------------------------------------

    accuracy = accuracy_score(
        y_test,
        pred
    )

    accuracies.append(
        accuracy
    )


    # Save model
    career_models[target_col] = model

    career_predictions[target_col] = {
        "actual": y_test,
        "predicted": pred
    }


    print(
        f"{target_col}: "
        f"{accuracy * 100:.2f}%"
    )


# =========================================================
# FINAL RESULTS
# =========================================================

print()
print("=" * 60)
print("HISTOGRAM GRADIENT BOOSTING CAREER ACCURACY")
print("=" * 60)

for i, accuracy in enumerate(accuracies, 1):

    print(
        f"top_career_{i}: "
        f"{accuracy * 100:.2f}%"
    )


print("=" * 60)

average_accuracy = np.mean(accuracies)

print(
    f"Average Accuracy: "
    f"{average_accuracy * 100:.2f}%"
)

print("=" * 60)

============================================================
top_career_1
============================================================
top_career_1: 80.50%
============================================================
top_career_2
============================================================
top_career_2: 69.50%
============================================================
top_career_3
============================================================
top_career_3: 72.75%
============================================================
top_career_4
============================================================
top_career_4: 70.25%
============================================================
top_career_5
============================================================
top_career_5: 69.00%

============================================================
HISTOGRAM GRADIENT BOOSTING CAREER ACCURACY
============================================================
top_career_1: 80.50%
top_career_2: 69.50%
top_career_3: 72.75%
top_career_4: 70.25%
top_career_5: 69.00%
============================================================
Average Accuracy: 72.40%
============================================================

In [74]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

# ============================================================
# HYPERPARAMETER TUNING
# ============================================================

tuned_models = {}
tuned_accuracies = []

for target_col in career_columns:

    print("=" * 60)
    print(target_col)
    print("=" * 60)

    y = df[target_col]

    # Remove missing values
    valid = y.notna()

    X_target = X_processed[valid]
    y_target = y[valid]

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X_target,
        y_target,
        test_size=0.20,
        random_state=42
    )

    # --------------------------------------------------------
    # Try several models
    # --------------------------------------------------------

    models = {

        "Random Forest": RandomForestClassifier(
            n_estimators=500,
            max_depth=None,
            min_samples_split=2,
            min_samples_leaf=1,
            max_features="sqrt",
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        ),

        "Extra Trees": ExtraTreesClassifier(
            n_estimators=500,
            max_depth=None,
            min_samples_split=2,
            min_samples_leaf=1,
            max_features="sqrt",
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        ),

        "Gradient Boosting": HistGradientBoostingClassifier(
            max_iter=500,
            learning_rate=0.05,
            max_leaf_nodes=31,
            min_samples_leaf=10,
            l2_regularization=2.0,
            random_state=42
        )
    }

    best_model = None
    best_accuracy = 0
    best_name = ""

    # --------------------------------------------------------
    # Test each model
    # --------------------------------------------------------

    for name, model_test in models.items():

        model_test.fit(
            X_train,
            y_train
        )

        pred = model_test.predict(
            X_test
        )

        accuracy = accuracy_score(
            y_test,
            pred
        )

        print(
            f"{name}: "
            f"{accuracy * 100:.2f}%"
        )

        if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_model = model_test
            best_name = name

    # Save best model
    tuned_models[target_col] = best_model
    tuned_accuracies.append(best_accuracy)

    print()
    print(
        f"BEST MODEL: {best_name}"
    )

    print(
        f"BEST ACCURACY: "
        f"{best_accuracy * 100:.2f}%"
    )

    print()


# ============================================================
# FINAL RESULTS
# ============================================================

print("=" * 60)
print("BEST MODEL RESULTS")
print("=" * 60)

for i, accuracy in enumerate(tuned_accuracies, 1):

    print(
        f"top_career_{i}: "
        f"{accuracy * 100:.2f}%"
    )

print("=" * 60)

average_accuracy = np.mean(
    tuned_accuracies
)

print(
    f"Average Accuracy: "
    f"{average_accuracy * 100:.2f}%"
)

print("=" * 60)

============================================================
top_career_1
============================================================
Random Forest: 75.00%
Extra Trees: 71.50%
Gradient Boosting: 79.50%

BEST MODEL: Gradient Boosting
BEST ACCURACY: 79.50%

============================================================
top_career_2
============================================================
Random Forest: 69.25%
Extra Trees: 66.25%
Gradient Boosting: 71.00%

BEST MODEL: Gradient Boosting
BEST ACCURACY: 71.00%

============================================================
top_career_3
============================================================
Random Forest: 68.25%
Extra Trees: 65.75%
Gradient Boosting: 71.25%

BEST MODEL: Gradient Boosting
BEST ACCURACY: 71.25%

============================================================
top_career_4
============================================================
Random Forest: 66.75%
Extra Trees: 63.25%
Gradient Boosting: 68.25%

BEST MODEL: Gradient Boosting
BEST ACCURACY: 68.25%

============================================================
top_career_5
============================================================
Random Forest: 67.25%
Extra Trees: 66.75%
Gradient Boosting: 68.50%

BEST MODEL: Gradient Boosting
BEST ACCURACY: 68.50%

============================================================
BEST MODEL RESULTS
============================================================
top_career_1: 79.50%
top_career_2: 71.00%
top_career_3: 71.25%
top_career_4: 68.25%
top_career_5: 68.50%
============================================================
Average Accuracy: 71.70%
============================================================

In [75]:
# ============================================================
# CREATE STRONGER CAREER FEATURES
# ============================================================

import numpy as np
import pandas as pd


df_model = df.copy()


# ============================================================
# ACADEMIC FEATURES
# ============================================================

df_model["academic_average"] = (
    df_model["grade_math"]
    + df_model["grade_science"]
    + df_model["grade_lang"]
    + df_model["grade_social"]
    + df_model["grade_cs"]
) / 5


df_model["stem_average"] = (
    df_model["grade_math"]
    + df_model["grade_science"]
    + df_model["grade_cs"]
) / 3


df_model["language_social_average"] = (
    df_model["grade_lang"]
    + df_model["grade_social"]
) / 2


# ============================================================
# APTITUDE FEATURES
# ============================================================

df_model["aptitude_average"] = (
    df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["score_verbal"]
    + df_model["score_creative"]
    + df_model["score_social"]
) / 5


df_model["logical_strength"] = (
    df_model["score_analytical"]
    + df_model["score_numeric"]
) / 2


df_model["communication_strength"] = (
    df_model["score_verbal"]
    + df_model["score_social"]
) / 2


df_model["creative_strength"] = (
    df_model["score_creative"]
    + df_model["score_verbal"]
) / 2


# ============================================================
# CAREER-RELATED COMBINATIONS
# ============================================================

df_model["technology_strength"] = (
    df_model["grade_cs"]
    + df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["hobby_coding"] * 100
    + df_model["hobby_robotics"] * 100
) / 5


df_model["science_strength"] = (
    df_model["grade_science"]
    + df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["hobby_science_experiments"] * 100
) / 4


df_model["business_strength"] = (
    df_model["score_numeric"]
    + df_model["score_social"]
    + df_model["score_verbal"]
    + df_model["hobby_business_trading"] * 100
) / 4


df_model["creative_strength_combined"] = (
    df_model["score_creative"]
    + df_model["grade_lang"]
    + df_model["hobby_drawing_art"] * 100
    + df_model["hobby_music"] * 100
    + df_model["hobby_writing"] * 100
    + df_model["hobby_fashion"] * 100
) / 6


df_model["social_strength"] = (
    df_model["score_social"]
    + df_model["score_verbal"]
    + df_model["grade_social"]
    + df_model["hobby_debating"] * 100
    + df_model["hobby_volunteering"] * 100
) / 5


# ============================================================
# HOBBY COUNT
# ============================================================

hobby_columns = [
    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading"
]


df_model["hobby_count"] = df_model[hobby_columns].sum(axis=1)


# ============================================================
# TOTAL STRENGTH
# ============================================================

df_model["overall_strength"] = (
    df_model["academic_average"]
    + df_model["aptitude_average"]
) / 2


# ============================================================
# CHECK
# ============================================================

print("=" * 60)
print("NEW FEATURES CREATED")
print("=" * 60)

new_features = [
    "academic_average",
    "stem_average",
    "language_social_average",
    "aptitude_average",
    "logical_strength",
    "communication_strength",
    "creative_strength",
    "technology_strength",
    "science_strength",
    "business_strength",
    "creative_strength_combined",
    "social_strength",
    "hobby_count",
    "overall_strength"
]

print("Number of new features:", len(new_features))

print()
print("New columns:")

for feature in new_features:
    print(feature)

print()
print("New dataset shape:")
print(df_model.shape)

============================================================
NEW FEATURES CREATED
============================================================
Number of new features: 14

New columns:
academic_average
stem_average
language_social_average
aptitude_average
logical_strength
communication_strength
creative_strength
technology_strength
science_strength
business_strength
creative_strength_combined
social_strength
hobby_count
overall_strength

New dataset shape:
(2000, 46)

In [76]:
# ============================================================
# TRAIN CAREER MODELS WITH ENGINEERED FEATURES
# ============================================================

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np


# ============================================================
# FEATURE COLUMNS
# ============================================================

base_features = [
    "field_filter",

    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading",

    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs",

    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"
]


new_features = [
    "academic_average",
    "stem_average",
    "language_social_average",
    "aptitude_average",
    "logical_strength",
    "communication_strength",
    "creative_strength",
    "technology_strength",
    "science_strength",
    "business_strength",
    "creative_strength_combined",
    "social_strength",
    "hobby_count",
    "overall_strength"
]


feature_columns = base_features + new_features


# ============================================================
# PREPARE X
# ============================================================

X = df_model[feature_columns].copy()

X["field_filter"] = X["field_filter"].astype(str)


# ============================================================
# ENCODE FIELD
# ============================================================

field_encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

X_field = field_encoder.fit_transform(
    X[["field_filter"]]
)


# ============================================================
# NUMERIC FEATURES
# ============================================================

X_numeric = X.drop(
    columns=["field_filter"]
).values


# Combine categorical + numeric
X_processed = np.hstack([
    X_field,
    X_numeric
])


# ============================================================
# CAREER TARGETS
# ============================================================

career_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]


# ============================================================
# TRAIN MODELS
# ============================================================

career_models_engineered = {}
engineered_accuracies = []


for target_col in career_columns:

    print("=" * 60)
    print(target_col)
    print("=" * 60)

    y = df_model[target_col]

    # Remove missing target values
    valid = y.notna()

    X_target = X_processed[valid]
    y_target = y[valid]


    # --------------------------------------------------------
    # TRAIN / TEST SPLIT
    # --------------------------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(
        X_target,
        y_target,
        test_size=0.20,
        random_state=42
    )


    # --------------------------------------------------------
    # GRADIENT BOOSTING
    # --------------------------------------------------------

    model = HistGradientBoostingClassifier(
        max_iter=500,
        learning_rate=0.05,
        max_leaf_nodes=31,
        min_samples_leaf=10,
        l2_regularization=2.0,
        random_state=42
    )


    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    model.fit(
        X_train,
        y_train
    )


    # --------------------------------------------------------
    # PREDICT
    # --------------------------------------------------------

    pred = model.predict(
        X_test
    )


    # --------------------------------------------------------
    # ACCURACY
    # --------------------------------------------------------

    accuracy = accuracy_score(
        y_test,
        pred
    )

    engineered_accuracies.append(
        accuracy
    )

    career_models_engineered[target_col] = model


    print(
        f"{target_col}: "
        f"{accuracy * 100:.2f}%"
    )


# ============================================================
# FINAL RESULTS
# ============================================================

print()
print("=" * 60)
print("ENGINEERED FEATURES - CAREER ACCURACY")
print("=" * 60)


for i, accuracy in enumerate(
    engineered_accuracies,
    1
):

    print(
        f"top_career_{i}: "
        f"{accuracy * 100:.2f}%"
    )


print("=" * 60)


average_accuracy = np.mean(
    engineered_accuracies
)


print(
    f"Average Accuracy: "
    f"{average_accuracy * 100:.2f}%"
)


print("=" * 60)

============================================================
top_career_1
============================================================
top_career_1: 81.00%
============================================================
top_career_2
============================================================
top_career_2: 75.25%
============================================================
top_career_3
============================================================
top_career_3: 76.00%
============================================================
top_career_4
============================================================
top_career_4: 71.75%
============================================================
top_career_5
============================================================
top_career_5: 72.25%

============================================================
ENGINEERED FEATURES - CAREER ACCURACY
============================================================
top_career_1: 81.00%
top_career_2: 75.25%
top_career_3: 76.00%
top_career_4: 71.75%
top_career_5: 72.25%
============================================================
Average Accuracy: 75.25%
============================================================

In [77]:
# ============================================================
# CAREER RECOMMENDATION - IMPROVED GRADIENT BOOSTING
# ============================================================

import pandas as pd
import numpy as np

from google.colab import files

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder


# ============================================================
# STEP 1 - UPLOAD DATASET
# ============================================================

print("=" * 60)
print("UPLOAD CAREER DATASET")
print("=" * 60)

uploaded = files.upload()

# Get uploaded filename
filename = list(uploaded.keys())[0]

print()
print("Uploaded file:", filename)


# ============================================================
# STEP 2 - LOAD DATASET
# ============================================================

df = pd.read_csv(filename)

print()
print("=" * 60)
print("DATASET LOADED")
print("=" * 60)

print("Shape:", df.shape)

print()
print("Columns:")
print(df.columns.tolist())


# ============================================================
# STEP 3 - BASIC FEATURE COLUMNS
# ============================================================

base_features = [

    "field_filter",

    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading",

    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs",

    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"
]


# ============================================================
# STEP 4 - CREATE COPY
# ============================================================

df_model = df.copy()


# ============================================================
# STEP 5 - ACADEMIC FEATURES
# ============================================================

df_model["academic_average"] = (
    df_model["grade_math"]
    + df_model["grade_science"]
    + df_model["grade_lang"]
    + df_model["grade_social"]
    + df_model["grade_cs"]
) / 5


df_model["stem_average"] = (
    df_model["grade_math"]
    + df_model["grade_science"]
    + df_model["grade_cs"]
) / 3


df_model["language_social_average"] = (
    df_model["grade_lang"]
    + df_model["grade_social"]
) / 2


# ============================================================
# STEP 6 - APTITUDE FEATURES
# ============================================================

df_model["aptitude_average"] = (
    df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["score_verbal"]
    + df_model["score_creative"]
    + df_model["score_social"]
) / 5


df_model["logical_strength"] = (
    df_model["score_analytical"]
    + df_model["score_numeric"]
) / 2


df_model["communication_strength"] = (
    df_model["score_verbal"]
    + df_model["score_social"]
) / 2


df_model["creative_strength"] = (
    df_model["score_creative"]
    + df_model["score_verbal"]
) / 2


# ============================================================
# STEP 7 - CAREER RELATED FEATURES
# ============================================================

df_model["technology_strength"] = (
    df_model["grade_cs"]
    + df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["hobby_coding"] * 100
    + df_model["hobby_robotics"] * 100
) / 5


df_model["science_strength"] = (
    df_model["grade_science"]
    + df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["hobby_science_experiments"] * 100
) / 4


df_model["business_strength"] = (
    df_model["score_numeric"]
    + df_model["score_social"]
    + df_model["score_verbal"]
    + df_model["hobby_business_trading"] * 100
) / 4


df_model["creative_strength_combined"] = (
    df_model["score_creative"]
    + df_model["grade_lang"]
    + df_model["hobby_drawing_art"] * 100
    + df_model["hobby_music"] * 100
    + df_model["hobby_writing"] * 100
    + df_model["hobby_fashion"] * 100
) / 6


df_model["social_strength"] = (
    df_model["score_social"]
    + df_model["score_verbal"]
    + df_model["grade_social"]
    + df_model["hobby_debating"] * 100
    + df_model["hobby_volunteering"] * 100
) / 5


# ============================================================
# STEP 8 - HOBBY COUNT
# ============================================================

hobby_columns = [

    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading"
]


df_model["hobby_count"] = (
    df_model[hobby_columns].sum(axis=1)
)


# ============================================================
# STEP 9 - OVERALL STRENGTH
# ============================================================

df_model["overall_strength"] = (
    df_model["academic_average"]
    + df_model["aptitude_average"]
) / 2


# ============================================================
# STEP 10 - NEW FEATURE LIST
# ============================================================

new_features = [

    "academic_average",
    "stem_average",
    "language_social_average",
    "aptitude_average",

    "logical_strength",
    "communication_strength",
    "creative_strength",

    "technology_strength",
    "science_strength",
    "business_strength",
    "creative_strength_combined",
    "social_strength",

    "hobby_count",
    "overall_strength"
]


feature_columns = base_features + new_features


# ============================================================
# STEP 11 - CHECK FEATURES
# ============================================================

missing_features = [
    col
    for col in feature_columns
    if col not in df_model.columns
]


if missing_features:

    print()
    print("❌ Missing features:")
    print(missing_features)

    raise ValueError(
        "Some required feature columns are missing."
    )


print()
print("=" * 60)
print("FEATURE ENGINEERING COMPLETE")
print("=" * 60)

print("Total features:", len(feature_columns))


# ============================================================
# STEP 12 - PREPARE X
# ============================================================

X = df_model[feature_columns].copy()

X["field_filter"] = (
    X["field_filter"]
    .astype(str)
)


# ============================================================
# STEP 13 - ENCODE FIELD
# ============================================================

field_encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)


X_field = field_encoder.fit_transform(
    X[["field_filter"]]
)


# ============================================================
# STEP 14 - NUMERIC FEATURES
# ============================================================

X_numeric = X.drop(
    columns=["field_filter"]
).values


# ============================================================
# STEP 15 - COMBINE FEATURES
# ============================================================

X_processed = np.hstack(
    [
        X_field,
        X_numeric
    ]
)


print()
print("Processed feature shape:", X_processed.shape)


# ============================================================
# STEP 16 - CAREER TARGETS
# ============================================================

career_columns = [

    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]


# ============================================================
# STEP 17 - TRAIN MODELS
# ============================================================

improved_models = {}
improved_accuracies = []


for target_col in career_columns:

    print()
    print("=" * 60)
    print(target_col)
    print("=" * 60)


    # --------------------------------------------------------
    # Target
    # --------------------------------------------------------

    y = df_model[target_col]


    # Remove missing values
    valid = y.notna()


    X_target = X_processed[valid]
    y_target = y[valid]


    # --------------------------------------------------------
    # Check class frequency
    # --------------------------------------------------------

    class_counts = y_target.value_counts()

    valid_classes = class_counts[
        class_counts >= 2
    ].index


    valid_mask = y_target.isin(
        valid_classes
    )


    X_target = X_target[valid_mask]
    y_target = y_target[valid_mask]


    print(
        "Samples:",
        len(y_target)
    )

    print(
        "Classes:",
        y_target.nunique()
    )


    # --------------------------------------------------------
    # Train/Test Split
    # --------------------------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(

        X_target,
        y_target,

        test_size=0.20,

        random_state=42,

        stratify=y_target
    )


    # ========================================================
    # MODEL
    # ========================================================

    if target_col == "top_career_1":

        model = HistGradientBoostingClassifier(

            max_iter=900,

            learning_rate=0.035,

            max_leaf_nodes=31,

            min_samples_leaf=5,

            l2_regularization=1.0,

            random_state=42
        )


    elif target_col == "top_career_2":

        model = HistGradientBoostingClassifier(

            max_iter=1000,

            learning_rate=0.03,

            max_leaf_nodes=31,

            min_samples_leaf=4,

            l2_regularization=0.8,

            random_state=42
        )


    elif target_col == "top_career_3":

        model = HistGradientBoostingClassifier(

            max_iter=1000,

            learning_rate=0.03,

            max_leaf_nodes=31,

            min_samples_leaf=4,

            l2_regularization=0.8,

            random_state=42
        )


    else:

        model = HistGradientBoostingClassifier(

            max_iter=1200,

            learning_rate=0.025,

            max_leaf_nodes=31,

            min_samples_leaf=3,

            l2_regularization=0.7,

            random_state=42
        )


    # ========================================================
    # TRAIN
    # ========================================================

    print("Training model...")


    model.fit(
        X_train,
        y_train
    )


    # ========================================================
    # PREDICT
    # ========================================================

    pred = model.predict(
        X_test
    )


    # ========================================================
    # ACCURACY
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        pred
    )


    improved_models[target_col] = model

    improved_accuracies.append(
        accuracy
    )


    print()
    print(
        f"{target_col}: "
        f"{accuracy * 100:.2f}%"
    )


# ============================================================
# FINAL RESULTS
# ============================================================

print()
print("=" * 60)
print("FINAL IMPROVED GRADIENT BOOSTING RESULTS")
print("=" * 60)


for i, accuracy in enumerate(
    improved_accuracies,
    1
):

    print(
        f"top_career_{i}: "
        f"{accuracy * 100:.2f}%"
    )


print("=" * 60)


average_accuracy = np.mean(
    improved_accuracies
)


print(
    f"Average Accuracy: "
    f"{average_accuracy * 100:.2f}%"
)


print("=" * 60)

============================================================
UPLOAD CAREER DATASET
============================================================

Saving career_training_data_cleaned.csv to career_training_data_cleaned (3).csv

Uploaded file: career_training_data_cleaned (3).csv

============================================================
DATASET LOADED
============================================================
Shape: (2000, 32)

Columns:
['field_filter', 'hobby_coding', 'hobby_gaming', 'hobby_reading', 'hobby_writing', 'hobby_music', 'hobby_drawing_art', 'hobby_sports', 'hobby_cooking', 'hobby_photography', 'hobby_travel', 'hobby_science_experiments', 'hobby_volunteering', 'hobby_debating', 'hobby_robotics', 'hobby_fashion', 'hobby_business_trading', 'grade_math', 'grade_science', 'grade_lang', 'grade_social', 'grade_cs', 'score_analytical', 'score_numeric', 'score_verbal', 'score_creative', 'score_social', 'top_career_1', 'top_career_2', 'top_career_3', 'top_career_4', 'top_career_5']

============================================================
FEATURE ENGINEERING COMPLETE
============================================================
Total features: 41

Processed feature shape: (2000, 60)

============================================================
top_career_1
============================================================
Samples: 1998
Classes: 44
Training model...

top_career_1: 84.75%

============================================================
top_career_2
============================================================
Samples: 1998
Classes: 55
Training model...

top_career_2: 75.50%

============================================================
top_career_3
============================================================
Samples: 1994
Classes: 59
Training model...

top_career_3: 74.44%

============================================================
top_career_4
============================================================
Samples: 1993
Classes: 63
Training model...

top_career_4: 74.69%

============================================================
top_career_5
============================================================
Samples: 1991
Classes: 63
Training model...

top_career_5: 72.68%

============================================================
FINAL IMPROVED GRADIENT BOOSTING RESULTS
============================================================
top_career_1: 84.75%
top_career_2: 75.50%
top_career_3: 74.44%
top_career_4: 74.69%
top_career_5: 72.68%
============================================================
Average Accuracy: 76.41%
============================================================

In [78]:
from google.colab import files

uploaded = files.upload()

Saving career_training_data_cleaned.csv to career_training_data_cleaned (4).csv

In [79]:
import os

print(os.listdir())

['.config', 'career_training_data_cleaned (2).csv', 'career_training_data_cleaned (1).csv', 'career_training_data_cleaned (4).csv', 'career_training_data_cleaned (3).csv', 'career_training_data_cleaned.csv', 'sample_data']

In [80]:
import pandas as pd

df = pd.read_csv("career_training_data_cleaned.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully!
Shape: (2000, 32)

,field_filter,hobby_coding,hobby_gaming,hobby_reading,hobby_writing,hobby_music,hobby_drawing_art,hobby_sports,hobby_cooking,hobby_photography,...,score_analytical,score_numeric,score_verbal,score_creative,score_social,top_career_1,top_career_2,top_career_3,top_career_4,top_career_5
0,all,0,0,0,0,0,1,0,0,0,...,96,97,62,78,66,Data Analyst,Data Scientist,Cybersecurity Analyst,Database Administrator,Systems Analyst
1,Defense,1,0,0,0,0,0,1,0,0,...,88,65,80,63,77,Defense Scientist,Navy Officer,Army Officer,Air Force Officer,Coast Guard Officer
2,all,0,0,1,1,0,0,0,0,0,...,74,77,91,81,92,Accountant,Chartered Accountant (CA),Marketing Manager,Human Resource Manager,Operations Manager
3,Forensics,0,0,1,0,1,0,0,0,0,...,60,64,56,67,68,Criminologist,Forensic Scientist,Crime Scene Investigator,Forensic Psychologist,Digital Forensics Analyst
4,all,1,0,1,1,0,1,0,0,0,...,75,57,76,58,65,Public Relations Manager,IT Project Manager,Animator,Film Director,Video Editor

In [81]:
# ============================================================
# RANKING-BASED CAREER EXPERIMENT
# ============================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd


# ============================================================
# CAREER TARGETS
# ============================================================

career_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]


# ============================================================
# STORE RESULTS
# ============================================================

ranking_results = {}

ranking_models = {}


# ============================================================
# TRAIN ONE MODEL FOR EACH CAREER POSITION
# ============================================================

for target_col in career_columns:

    print()
    print("=" * 60)
    print(target_col)
    print("=" * 60)

    y = df_model[target_col]

    # Remove missing values
    valid = y.notna()

    X_target = X_processed[valid]
    y_target = y[valid]

    # Remove classes with only one sample
    class_counts = y_target.value_counts()

    valid_classes = class_counts[
        class_counts >= 2
    ].index

    keep = y_target.isin(valid_classes)

    X_target = X_target[keep]
    y_target = y_target[keep]

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X_target,
        y_target,
        test_size=0.20,
        random_state=42,
        stratify=y_target
    )

    # Model
    model = RandomForestClassifier(
        n_estimators=500,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        max_features="sqrt",
        class_weight="balanced_subsample",
        random_state=42,
        n_jobs=-1
    )

    print("Training...")

    model.fit(
        X_train,
        y_train
    )

    # Prediction
    pred = model.predict(
        X_test
    )

    accuracy = accuracy_score(
        y_test,
        pred
    )

    ranking_models[target_col] = model
    ranking_results[target_col] = accuracy

    print(
        f"Accuracy: {accuracy * 100:.2f}%"
    )


# ============================================================
# RESULTS
# ============================================================

print()
print("=" * 60)
print("RANKING EXPERIMENT RESULTS")
print("=" * 60)

for target_col, accuracy in ranking_results.items():

    print(
        f"{target_col}: "
        f"{accuracy * 100:.2f}%"
    )


average = np.mean(
    list(ranking_results.values())
)

print("=" * 60)

print(
    f"Average Accuracy: "
    f"{average * 100:.2f}%"
)

print("=" * 60)


# ============================================================
# COMPARE WITH CURRENT MODEL
# ============================================================

current_average = 76.41

print()
print("=" * 60)
print("COMPARISON")
print("=" * 60)

print(
    f"Current model: "
    f"{current_average:.2f}%"
)

print(
    f"New experiment: "
    f"{average * 100:.2f}%"
)

difference = (
    average * 100
    - current_average
)

print(
    f"Difference: "
    f"{difference:+.2f}%"
)

print("=" * 60)

============================================================
top_career_1
============================================================
Training...
Accuracy: 79.25%

============================================================
top_career_2
============================================================
Training...
Accuracy: 73.75%

============================================================
top_career_3
============================================================
Training...
Accuracy: 75.19%

============================================================
top_career_4
============================================================
Training...
Accuracy: 72.68%

============================================================
top_career_5
============================================================
Training...
Accuracy: 72.93%

============================================================
RANKING EXPERIMENT RESULTS
============================================================
top_career_1: 79.25%
top_career_2: 73.75%
top_career_3: 75.19%
top_career_4: 72.68%
top_career_5: 72.93%
============================================================
Average Accuracy: 74.76%
============================================================

============================================================
COMPARISON
============================================================
Current model: 76.41%
New experiment: 74.76%
Difference: -1.65%
============================================================

In [82]:
# ============================================================
# FEATURE IMPORTANCE ANALYSIS
# ============================================================

print("=" * 60)
print("FEATURE IMPORTANCE ANALYSIS")
print("=" * 60)

# Get feature names after OneHotEncoding

field_feature_names = list(
    field_encoder.get_feature_names_out(["field_filter"])
)

numeric_feature_names = [
    col for col in feature_columns
    if col != "field_filter"
]

all_feature_names = (
    field_feature_names
    + numeric_feature_names
)


# ============================================================
# ANALYZE EACH CAREER MODEL
# ============================================================

for target_col in career_columns:

    print()
    print("=" * 60)
    print(target_col)
    print("=" * 60)

    model = improved_models[target_col]

    # HistGradientBoosting uses feature_importances_
    # only in some sklearn versions.
    # If unavailable, skip safely.

    if hasattr(model, "feature_importances_"):

        importance = model.feature_importances_

        importance_df = pd.DataFrame({
            "Feature": all_feature_names,
            "Importance": importance
        })

        importance_df = importance_df.sort_values(
            "Importance",
            ascending=False
        )

        print(
            importance_df.head(15).to_string(
                index=False
            )
        )

    else:

        print(
            "Feature importance is not directly available "
            "for this HistGradientBoosting model."
        )

print()
print("=" * 60)
print("ANALYSIS COMPLETE")
print("=" * 60)

============================================================
FEATURE IMPORTANCE ANALYSIS
============================================================

============================================================
top_career_1
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
top_career_2
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
top_career_3
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
top_career_4
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
top_career_5
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
ANALYSIS COMPLETE
============================================================

In [83]:
# ============================================================
# FEATURE IMPORTANCE ANALYSIS
# ============================================================

print("=" * 60)
print("FEATURE IMPORTANCE ANALYSIS")
print("=" * 60)

# Get feature names after OneHotEncoding

field_feature_names = list(
    field_encoder.get_feature_names_out(["field_filter"])
)

numeric_feature_names = [
    col for col in feature_columns
    if col != "field_filter"
]

all_feature_names = (
    field_feature_names
    + numeric_feature_names
)


# ============================================================
# ANALYZE EACH CAREER MODEL
# ============================================================

for target_col in career_columns:

    print()
    print("=" * 60)
    print(target_col)
    print("=" * 60)

    model = improved_models[target_col]

    # HistGradientBoosting uses feature_importances_
    # only in some sklearn versions.
    # If unavailable, skip safely.

    if hasattr(model, "feature_importances_"):

        importance = model.feature_importances_

        importance_df = pd.DataFrame({
            "Feature": all_feature_names,
            "Importance": importance
        })

        importance_df = importance_df.sort_values(
            "Importance",
            ascending=False
        )

        print(
            importance_df.head(15).to_string(
                index=False
            )
        )

    else:

        print(
            "Feature importance is not directly available "
            "for this HistGradientBoosting model."
        )

print()
print("=" * 60)
print("ANALYSIS COMPLETE")
print("=" * 60)

============================================================
FEATURE IMPORTANCE ANALYSIS
============================================================

============================================================
top_career_1
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
top_career_2
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
top_career_3
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
top_career_4
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
top_career_5
============================================================
Feature importance is not directly available for this HistGradientBoosting model.

============================================================
ANALYSIS COMPLETE
============================================================

In [84]:
# ============================================================
# PERMUTATION FEATURE IMPORTANCE
# ============================================================

from sklearn.inspection import permutation_importance

print("=" * 60)
print("PERMUTATION FEATURE IMPORTANCE")
print("=" * 60)


# Feature names
field_feature_names = list(
    field_encoder.get_feature_names_out(["field_filter"])
)

numeric_feature_names = [
    col
    for col in feature_columns
    if col != "field_filter"
]

all_feature_names = (
    field_feature_names
    + numeric_feature_names
)


# ============================================================
# ANALYZE EACH CAREER
# ============================================================

for target_col in career_columns:

    print()
    print("=" * 60)
    print(target_col)
    print("=" * 60)

    # Get the model we already trained
    model = improved_models[target_col]

    # Prepare target
    y = df_model[target_col]

    valid = y.notna()

    X_target = X_processed[valid]
    y_target = y[valid]

    # Remove classes with only one sample
    class_counts = y_target.value_counts()

    valid_classes = class_counts[
        class_counts >= 2
    ].index

    keep = y_target.isin(valid_classes)

    X_target = X_target[keep]
    y_target = y_target[keep]


    # Same train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X_target,
        y_target,
        test_size=0.20,
        random_state=42,
        stratify=y_target
    )


    # ========================================================
    # PERMUTATION IMPORTANCE
    # ========================================================

    print("Calculating importance...")

    result = permutation_importance(
        model,
        X_test,
        y_test,
        n_repeats=5,
        random_state=42,
        scoring="accuracy",
        n_jobs=-1
    )


    importance_df = pd.DataFrame({
        "Feature": all_feature_names,
        "Importance": result.importances_mean
    })


    importance_df = importance_df.sort_values(
        "Importance",
        ascending=False
    )


    print()
    print("TOP 15 IMPORTANT FEATURES")
    print("-" * 60)

    print(
        importance_df.head(15).to_string(
            index=False
        )
    )


print()
print("=" * 60)
print("PERMUTATION IMPORTANCE COMPLETE")
print("=" * 60)

============================================================
PERMUTATION FEATURE IMPORTANCE
============================================================

============================================================
top_career_1
============================================================
Calculating importance...

KeyboardInterrupt:

In [85]:
# ============================================================
# OPTIMIZED GRADIENT BOOSTING - COMPLETE SELF-CONTAINED CELL
# ============================================================

import pandas as pd
import numpy as np

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder


# ============================================================
# 1. LOAD DATASET
# ============================================================

file_path = "career_training_data_cleaned (1).csv"

df = pd.read_csv(file_path)

print("=" * 60)
print("DATASET LOADED")
print("=" * 60)

print("Shape:", df.shape)


# ============================================================
# 2. CAREER TARGET COLUMNS
# ============================================================

career_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]


# ============================================================
# 3. BASE FEATURES
# ============================================================

base_features = [

    "field_filter",

    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading",

    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs",

    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"
]


# ============================================================
# 4. CREATE COPY
# ============================================================

df_model = df.copy()


# ============================================================
# 5. ACADEMIC FEATURES
# ============================================================

df_model["academic_average"] = (
    df_model["grade_math"]
    + df_model["grade_science"]
    + df_model["grade_lang"]
    + df_model["grade_social"]
    + df_model["grade_cs"]
) / 5


df_model["stem_average"] = (
    df_model["grade_math"]
    + df_model["grade_science"]
    + df_model["grade_cs"]
) / 3


df_model["language_social_average"] = (
    df_model["grade_lang"]
    + df_model["grade_social"]
) / 2


# ============================================================
# 6. APTITUDE FEATURES
# ============================================================

df_model["aptitude_average"] = (
    df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["score_verbal"]
    + df_model["score_creative"]
    + df_model["score_social"]
) / 5


df_model["logical_strength"] = (
    df_model["score_analytical"]
    + df_model["score_numeric"]
) / 2


df_model["communication_strength"] = (
    df_model["score_verbal"]
    + df_model["score_social"]
) / 2


df_model["creative_strength"] = (
    df_model["score_creative"]
    + df_model["score_verbal"]
) / 2


# ============================================================
# 7. CAREER-RELATED FEATURES
# ============================================================

df_model["technology_strength"] = (
    df_model["grade_cs"]
    + df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["hobby_coding"] * 100
    + df_model["hobby_robotics"] * 100
) / 5


df_model["science_strength"] = (
    df_model["grade_science"]
    + df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["hobby_science_experiments"] * 100
) / 4


df_model["business_strength"] = (
    df_model["score_numeric"]
    + df_model["score_social"]
    + df_model["score_verbal"]
    + df_model["hobby_business_trading"] * 100
) / 4


df_model["creative_strength_combined"] = (
    df_model["score_creative"]
    + df_model["grade_lang"]
    + df_model["hobby_drawing_art"] * 100
    + df_model["hobby_music"] * 100
    + df_model["hobby_writing"] * 100
    + df_model["hobby_fashion"] * 100
) / 6


df_model["social_strength"] = (
    df_model["score_social"]
    + df_model["score_verbal"]
    + df_model["grade_social"]
    + df_model["hobby_debating"] * 100
    + df_model["hobby_volunteering"] * 100
) / 5


# ============================================================
# 8. HOBBY COUNT
# ============================================================

hobby_columns = [
    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading"
]


df_model["hobby_count"] = (
    df_model[hobby_columns].sum(axis=1)
)


# ============================================================
# 9. OVERALL STRENGTH
# ============================================================

df_model["overall_strength"] = (
    df_model["academic_average"]
    + df_model["aptitude_average"]
) / 2


# ============================================================
# 10. ALL FEATURES
# ============================================================

new_features = [

    "academic_average",
    "stem_average",
    "language_social_average",
    "aptitude_average",
    "logical_strength",
    "communication_strength",
    "creative_strength",
    "technology_strength",
    "science_strength",
    "business_strength",
    "creative_strength_combined",
    "social_strength",
    "hobby_count",
    "overall_strength"
]


feature_columns = base_features + new_features


print()
print("=" * 60)
print("FEATURE ENGINEERING COMPLETE")
print("=" * 60)

print("Total features:", len(feature_columns))


# ============================================================
# 11. PREPARE X
# ============================================================

X = df_model[feature_columns].copy()

X["field_filter"] = X["field_filter"].astype(str)


# ============================================================
# 12. ONE-HOT ENCODE FIELD
# ============================================================

field_encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)


X_field = field_encoder.fit_transform(
    X[["field_filter"]]
)


# ============================================================
# 13. NUMERIC FEATURES
# ============================================================

X_numeric = X.drop(
    columns=["field_filter"]
).values


# ============================================================
# 14. COMBINE FEATURES
# ============================================================

X_processed = np.hstack([
    X_field,
    X_numeric
])


print("Processed feature shape:", X_processed.shape)


# ============================================================
# 15. MODEL SETTINGS
# ============================================================

settings = [

    {
        "max_iter": 500,
        "learning_rate": 0.04,
        "max_leaf_nodes": 31,
        "min_samples_leaf": 5,
        "l2_regularization": 1.0
    },

    {
        "max_iter": 600,
        "learning_rate": 0.03,
        "max_leaf_nodes": 63,
        "min_samples_leaf": 5,
        "l2_regularization": 1.0
    },

    {
        "max_iter": 700,
        "learning_rate": 0.03,
        "max_leaf_nodes": 31,
        "min_samples_leaf": 3,
        "l2_regularization": 2.0
    }
]


# ============================================================
# 16. TRAIN MODELS
# ============================================================

tuned_models = {}
tuned_accuracies = {}


for target_col in career_columns:

    print()
    print("=" * 60)
    print(target_col)
    print("=" * 60)

    y = df_model[target_col]

    # Remove missing target values
    valid = y.notna()

    X_target = X_processed[valid]
    y_target = y[valid]


    # --------------------------------------------------------
    # Remove classes with only ONE sample
    # --------------------------------------------------------

    class_counts = y_target.value_counts()

    valid_classes = class_counts[
        class_counts >= 2
    ].index

    keep = y_target.isin(valid_classes)

    X_target = X_target[keep]
    y_target = y_target[keep]


    print("Samples:", len(y_target))
    print("Classes:", y_target.nunique())


    # --------------------------------------------------------
    # Train/Test Split
    # --------------------------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(

        X_target,
        y_target,

        test_size=0.20,

        random_state=42,

        stratify=y_target
    )


    best_accuracy = 0
    best_model = None
    best_setting = None


    # --------------------------------------------------------
    # TEST DIFFERENT SETTINGS
    # --------------------------------------------------------

    for number, params in enumerate(settings, 1):

        print(
            f"Testing configuration "
            f"{number}/{len(settings)}..."
        )


        model = HistGradientBoostingClassifier(

            max_iter=params["max_iter"],

            learning_rate=params["learning_rate"],

            max_leaf_nodes=params["max_leaf_nodes"],

            min_samples_leaf=params["min_samples_leaf"],

            l2_regularization=params["l2_regularization"],

            early_stopping=True,

            random_state=42
        )


        model.fit(
            X_train,
            y_train
        )


        pred = model.predict(
            X_test
        )


        accuracy = accuracy_score(
            y_test,
            pred
        )


        print(
            f"  Accuracy: "
            f"{accuracy * 100:.2f}%"
        )


        # Keep best
        if accuracy > best_accuracy:

            best_accuracy = accuracy

            best_model = model

            best_setting = number


    # --------------------------------------------------------
    # SAVE BEST
    # --------------------------------------------------------

    tuned_models[target_col] = best_model

    tuned_accuracies[target_col] = best_accuracy


    print()
    print(
        f"BEST FOR {target_col}: "
        f"{best_accuracy * 100:.2f}%"
    )

    print(
        f"Configuration: {best_setting}"
    )


# ============================================================
# 17. FINAL RESULTS
# ============================================================

print()
print("=" * 60)
print("TUNED GRADIENT BOOSTING RESULTS")
print("=" * 60)


for target_col in career_columns:

    accuracy = tuned_accuracies[target_col]

    print(
        f"{target_col}: "
        f"{accuracy * 100:.2f}%"
    )


average_accuracy = np.mean(
    list(tuned_accuracies.values())
)


print("=" * 60)

print(
    f"Average Accuracy: "
    f"{average_accuracy * 100:.2f}%"
)

print("=" * 60)


# ============================================================
# 18. OLD VS NEW
# ============================================================

old_average = 76.41

new_average = average_accuracy * 100

print()
print("=" * 60)
print("OLD VS NEW")
print("=" * 60)

print(
    f"Old average: "
    f"{old_average:.2f}%"
)

print(
    f"New average: "
    f"{new_average:.2f}%"
)

print(
    f"Improvement: "
    f"{new_average - old_average:+.2f}%"
)

print("=" * 60)

============================================================
DATASET LOADED
============================================================
Shape: (2000, 32)

============================================================
FEATURE ENGINEERING COMPLETE
============================================================
Total features: 41
Processed feature shape: (2000, 60)

============================================================
top_career_1
============================================================
Samples: 1998
Classes: 44
Testing configuration 1/3...
  Accuracy: 84.75%
Testing configuration 2/3...
  Accuracy: 84.00%
Testing configuration 3/3...
  Accuracy: 85.25%

BEST FOR top_career_1: 85.25%
Configuration: 3

============================================================
top_career_2
============================================================
Samples: 1998
Classes: 55
Testing configuration 1/3...
  Accuracy: 77.50%
Testing configuration 2/3...
  Accuracy: 77.50%
Testing configuration 3/3...
  Accuracy: 77.00%

BEST FOR top_career_2: 77.50%
Configuration: 1

============================================================
top_career_3
============================================================
Samples: 1994
Classes: 59
Testing configuration 1/3...
  Accuracy: 74.44%
Testing configuration 2/3...
  Accuracy: 73.93%
Testing configuration 3/3...
  Accuracy: 74.69%

BEST FOR top_career_3: 74.69%
Configuration: 3

============================================================
top_career_4
============================================================
Samples: 1993
Classes: 63
Testing configuration 1/3...
  Accuracy: 71.68%
Testing configuration 2/3...
  Accuracy: 71.43%
Testing configuration 3/3...
  Accuracy: 71.93%

BEST FOR top_career_4: 71.93%
Configuration: 3

============================================================
top_career_5
============================================================
Samples: 1991
Classes: 63
Testing configuration 1/3...
  Accuracy: 72.68%
Testing configuration 2/3...
  Accuracy: 73.43%
Testing configuration 3/3...
  Accuracy: 72.43%

BEST FOR top_career_5: 73.43%
Configuration: 2

============================================================
TUNED GRADIENT BOOSTING RESULTS
============================================================
top_career_1: 85.25%
top_career_2: 77.50%
top_career_3: 74.69%
top_career_4: 71.93%
top_career_5: 73.43%
============================================================
Average Accuracy: 76.56%
============================================================

============================================================
OLD VS NEW
============================================================
Old average: 76.41%
New average: 76.56%
Improvement: +0.15%
============================================================

In [86]:
import joblib

# ============================================================
# SAVE FINAL CAREER RECOMMENDATION MODEL
# ============================================================

model_data = {

    # Trained models for all 5 career positions
    "models": tuned_models,

    # Encoder used for field_filter
    "field_encoder": field_encoder,

    # Feature information
    "feature_columns": feature_columns,

    "base_features": base_features,

    "new_features": new_features,

    # Career target columns
    "career_columns": career_columns,

    # Keep the accuracy results
    "accuracies": tuned_accuracies
}


# ============================================================
# SAVE
# ============================================================

model_filename = "career_recommendation_model.pkl"

joblib.dump(
    model_data,
    model_filename
)


print("=" * 60)
print("MODEL SAVED SUCCESSFULLY")
print("=" * 60)

print("File:", model_filename)

print()
print("Saved models:")

for career in career_columns:
    print(
        f"{career}: "
        f"{tuned_accuracies[career] * 100:.2f}%"
    )

print()
print(
    f"Average Accuracy: "
    f"{np.mean(list(tuned_accuracies.values())) * 100:.2f}%"
)

print("=" * 60)

============================================================
MODEL SAVED SUCCESSFULLY
============================================================
File: career_recommendation_model.pkl

Saved models:
top_career_1: 85.25%
top_career_2: 77.50%
top_career_3: 74.69%
top_career_4: 71.93%
top_career_5: 73.43%

Average Accuracy: 76.56%
============================================================

In [89]:
import streamlit as st
import pandas as pd
import numpy as np
import joblib
from pathlib import Path


# ============================================================
# PAGE SETTINGS
# ============================================================

st.set_page_config(
    page_title="Career Recommendation System",
    page_icon="🎓",
    layout="wide"
)


# ============================================================
# LOAD SAVED MODEL
# ============================================================

@st.cache_resource
def load_model():

    model_path = (
        Path(__file__).parent
        / "career_recommendation_model.pkl"
    )

    if not model_path.exists():

        st.error(
            "❌ career_recommendation_model.pkl "
            "was not found."
        )

        st.info(
            "Make sure the .pkl file is in the "
            "same folder as app.py."
        )

        st.stop()

    try:

        data = joblib.load(model_path)

        return data

    except Exception as e:

        st.error(
            "❌ Could not load the career model."
        )

        st.code(str(e))

        st.stop()


data = load_model()


models = data["models"]
field_encoder = data["field_encoder"]
feature_columns = data["feature_columns"]
base_features = data["base_features"]
new_features = data["new_features"]
career_columns = data["career_columns"]


# ============================================================
# TITLE
# ============================================================

st.title("🎓 Career Recommendation System")

st.write(
    "Enter your field, hobbies, grades and aptitude "
    "scores to get your Top 5 career recommendations."
)


st.divider()


# ============================================================
# FIELD
# ============================================================

st.subheader("🎓 Select Your Field")

fields = list(
    field_encoder.categories_[0]
)

field = st.selectbox(
    "Choose your field",
    fields,
    key="field_selection"
)


# ============================================================
# STUDENT DATA
# ============================================================

student = {
    "field_filter": field
}


# ============================================================
# HOBBIES
# ============================================================

st.subheader("🎯 Hobbies")

hobby_columns = [

    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading"
]


cols = st.columns(4)


for i, hobby in enumerate(hobby_columns):

    hobby_name = (
        hobby
        .replace("hobby_", "")
        .replace("_", " ")
        .title()
    )

    with cols[i % 4]:

        selected = st.checkbox(
            hobby_name,
            value=False,
            key=f"hobby_{hobby}"
        )

    student[hobby] = (
        1 if selected else 0
    )


st.divider()


# ============================================================
# GRADES
# ============================================================

st.subheader("📚 Academic Grades")

grade_columns = [

    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs"
]


grade_names = {

    "grade_math": "Math",

    "grade_science": "Science",

    "grade_lang": "Language",

    "grade_social": "Social Science",

    "grade_cs": "Computer Science"
}


cols = st.columns(5)


for i, grade_col in enumerate(
    grade_columns
):

    with cols[i]:

        student[grade_col] = st.number_input(

            grade_names[grade_col],

            min_value=0.0,

            max_value=100.0,

            value=50.0,

            step=1.0,

            key=f"grade_{grade_col}"
        )


st.divider()


# ============================================================
# APTITUDE SCORES
# ============================================================

st.subheader("🧠 Aptitude Scores")

score_columns = [

    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"
]


score_names = {

    "score_analytical": "Analytical",

    "score_numeric": "Numeric",

    "score_verbal": "Verbal",

    "score_creative": "Creative",

    "score_social": "Social"
}


cols = st.columns(5)


for i, score_col in enumerate(
    score_columns
):

    with cols[i]:

        student[score_col] = st.number_input(

            score_names[score_col],

            min_value=0.0,

            max_value=100.0,

            value=50.0,

            step=1.0,

            key=f"score_{score_col}"
        )


# ============================================================
# PREDICTION BUTTON
# ============================================================

st.divider()

predict = st.button(

    "🔮 Predict Top 5 Careers",

    use_container_width=True,

    type="primary",

    key="predict_button"
)


# ============================================================
# FEATURE ENGINEERING FUNCTION
# ============================================================

def create_features(student):

    df = pd.DataFrame([student])


    # --------------------------------------------------------
    # Academic features
    # --------------------------------------------------------

    df["academic_average"] = (

        df["grade_math"]

        + df["grade_science"]

        + df["grade_lang"]

        + df["grade_social"]

        + df["grade_cs"]

    ) / 5


    df["stem_average"] = (

        df["grade_math"]

        + df["grade_science"]

        + df["grade_cs"]

    ) / 3


    df["language_social_average"] = (

        df["grade_lang"]

        + df["grade_social"]

    ) / 2


    # --------------------------------------------------------
    # Aptitude features
    # --------------------------------------------------------

    df["aptitude_average"] = (

        df["score_analytical"]

        + df["score_numeric"]

        + df["score_verbal"]

        + df["score_creative"]

        + df["score_social"]

    ) / 5


    df["logical_strength"] = (

        df["score_analytical"]

        + df["score_numeric"]

    ) / 2


    df["communication_strength"] = (

        df["score_verbal"]

        + df["score_social"]

    ) / 2


    df["creative_strength"] = (

        df["score_creative"]

        + df["score_verbal"]

    ) / 2


    # --------------------------------------------------------
    # Career-related features
    # --------------------------------------------------------

    df["technology_strength"] = (

        df["grade_cs"]

        + df["score_analytical"]

        + df["score_numeric"]

        + df["hobby_coding"] * 100

        + df["hobby_robotics"] * 100

    ) / 5


    df["science_strength"] = (

        df["grade_science"]

        + df["score_analytical"]

        + df["score_numeric"]

        + df["hobby_science_experiments"] * 100

    ) / 4


    df["business_strength"] = (

        df["score_numeric"]

        + df["score_social"]

        + df["score_verbal"]

        + df["hobby_business_trading"] * 100

    ) / 4


    df["creative_strength_combined"] = (

        df["score_creative"]

        + df["grade_lang"]

        + df["hobby_drawing_art"] * 100

        + df["hobby_music"] * 100

        + df["hobby_writing"] * 100

        + df["hobby_fashion"] * 100

    ) / 6


    df["social_strength"] = (

        df["score_social"]

        + df["score_verbal"]

        + df["grade_social"]

        + df["hobby_debating"] * 100

        + df["hobby_volunteering"] * 100

    ) / 5


    # --------------------------------------------------------
    # Hobby count
    # --------------------------------------------------------

    df["hobby_count"] = (

        df[hobby_columns].sum(axis=1)

    )


    # --------------------------------------------------------
    # Overall strength
    # --------------------------------------------------------

    df["overall_strength"] = (

        df["academic_average"]

        + df["aptitude_average"]

    ) / 2


    return df


# ============================================================
# PREDICTION
# ============================================================

if predict:

    try:

        # ----------------------------------------------------
        # Create engineered features
        # ----------------------------------------------------

        student_df = create_features(student)


        # ----------------------------------------------------
        # Select exactly the training features
        # ----------------------------------------------------

        X = student_df[
            feature_columns
        ].copy()


        # ----------------------------------------------------
        # Encode field
        # ----------------------------------------------------

        X["field_filter"] = (
            X["field_filter"].astype(str)
        )


        X_field = field_encoder.transform(
            X[["field_filter"]]
        )


        # ----------------------------------------------------
        # Numeric features
        # ----------------------------------------------------

        X_numeric = X.drop(
            columns=["field_filter"]
        ).values


        # ----------------------------------------------------
        # Combine features
        # ----------------------------------------------------

        X_processed = np.hstack([

            X_field,

            X_numeric

        ])


        # ----------------------------------------------------
        # Display results
        # ----------------------------------------------------

        st.divider()

        st.subheader(
            "🏆 Your Top 5 Career Recommendations"
        )


        for i, career_col in enumerate(
            career_columns
        ):

            model = models[career_col]


            prediction = model.predict(
                X_processed
            )[0]


            # ------------------------------------------------
            # Career IDs are stored in the dataset.
            # Display the predicted career ID for now.
            # ------------------------------------------------

            career_name = str(
                prediction
            )


            if i == 0:

                st.success(
                    f"🥇 **1. Career ID: "
                    f"{career_name}**"
                )

            elif i == 1:

                st.info(
                    f"🥈 **2. Career ID: "
                    f"{career_name}**"
                )

            elif i == 2:

                st.warning(
                    f"🥉 **3. Career ID: "
                    f"{career_name}**"
                )

            else:

                st.write(
                    f"### {i + 1}. "
                    f"Career ID: {career_name}"
                )


        # ----------------------------------------------------
        # Input summary
        # ----------------------------------------------------

        with st.expander(
            "📋 View Your Input"
        ):

            st.dataframe(
                student_df,
                use_container_width=True
            )


    except Exception as e:

        st.error(
            "❌ Prediction failed."
        )

        st.code(
            str(e)
        )

        st.info(
            "Please make sure the app uses the "
            "same feature engineering and model "
            "files used during training."
        )

ModuleNotFoundError: No module named 'streamlit'

In [90]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.62.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.52.4)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.25.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.19)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.62.0-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 70.2 MB/s eta 0:00:00
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 46.5 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.3 streamlit-1.62.0

In [91]:
import streamlit as st

print("Streamlit installed successfully!")
print("Version:", st.__version__)

Streamlit installed successfully!
Version: 1.62.0

In [92]:
%%writefile app.py

# Paste the complete Streamlit code I gave you above here

Writing app.py

In [93]:
from google.colab import files

uploaded = files.upload()

Saving career_training_data_cleaned.csv to career_training_data_cleaned (5).csv

In [94]:
import os

print(os.listdir())

['.config', 'career_training_data_cleaned (2).csv', 'career_training_data_cleaned (1).csv', 'career_recommendation_model.pkl', 'career_training_data_cleaned (4).csv', 'career_training_data_cleaned (3).csv', 'app.py', 'career_training_data_cleaned.csv', 'career_training_data_cleaned (5).csv', 'sample_data']

In [14]:
%%writefile app.py

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from pathlib import Path


# ============================================================
# PAGE SETTINGS
# ============================================================

st.set_page_config(
    page_title="Career Recommendation System",
    page_icon="🎓",
    layout="wide"
)


# ============================================================
# LOAD MODEL
# ============================================================

@st.cache_resource
def load_model():

    model_path = Path(__file__).parent / "career_ranking_model.pkl"

    if not model_path.exists():

        st.error(
            "❌ career_ranking_model.pkl not found."
        )

        st.stop()

    return joblib.load(model_path)


data = load_model()

ranking_model = data["model"]
feature_columns = data["feature_columns"]


# ============================================================
# TITLE
# ============================================================

st.title("🎓 Career Recommendation System")

st.write(
    "Enter your field, hobbies, academic grades and aptitude "
    "scores to receive your Top 5 career recommendations."
)


# ============================================================
# FIELD
# ============================================================

st.subheader("🎓 Select Your Field")

fields = [
    "Engineering",
    "Medical & Healthcare",
    "Business & Finance",
    "Science & Research",
    "Arts & Design",
    "Computer Science & IT",
    "Education",
    "Law & Government",
    "Media & Communication",
    "Sports & Fitness"
]

field = st.selectbox(
    "Choose your field",
    fields
)


# ============================================================
# STUDENT DATA
# ============================================================

student = {}


# ============================================================
# HOBBIES
# ============================================================

st.subheader("🎯 Hobbies")

hobby_columns = [

    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading"

]


cols = st.columns(4)


for i, hobby in enumerate(hobby_columns):

    name = (
        hobby
        .replace("hobby_", "")
        .replace("_", " ")
        .title()
    )

    with cols[i % 4]:

        selected = st.checkbox(name)

    student[hobby] = 1 if selected else 0


# ============================================================
# ACADEMIC GRADES
# ============================================================

st.subheader("📚 Academic Grades")

grade_columns = [

    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs"

]


grade_names = {

    "grade_math": "Math",
    "grade_science": "Science",
    "grade_lang": "Language",
    "grade_social": "Social Science",
    "grade_cs": "Computer Science"

}


cols = st.columns(5)


for i, grade in enumerate(grade_columns):

    with cols[i]:

        student[grade] = st.number_input(

            grade_names[grade],

            min_value=0.0,
            max_value=100.0,
            value=50.0,
            step=1.0

        )


# ============================================================
# APTITUDE SCORES
# ============================================================

st.subheader("🧠 Aptitude Scores")

score_columns = [

    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"

]


score_names = {

    "score_analytical": "Analytical",
    "score_numeric": "Numeric",
    "score_verbal": "Verbal",
    "score_creative": "Creative",
    "score_social": "Social"

}


cols = st.columns(5)


for i, score in enumerate(score_columns):

    with cols[i]:

        student[score] = st.number_input(

            score_names[score],

            min_value=0.0,
            max_value=100.0,
            value=50.0,
            step=1.0

        )


# ============================================================
# FEATURE ENGINEERING
# ============================================================

def create_features(student):

    df = pd.DataFrame([student])


    # --------------------------------------------------------
    # Academic
    # --------------------------------------------------------

    df["academic_average"] = (

        df["grade_math"]
        + df["grade_science"]
        + df["grade_lang"]
        + df["grade_social"]
        + df["grade_cs"]

    ) / 5


    df["stem_average"] = (

        df["grade_math"]
        + df["grade_science"]
        + df["grade_cs"]

    ) / 3


    df["language_social_average"] = (

        df["grade_lang"]
        + df["grade_social"]

    ) / 2


    # --------------------------------------------------------
    # Aptitude
    # --------------------------------------------------------

    df["aptitude_average"] = (

        df["score_analytical"]
        + df["score_numeric"]
        + df["score_verbal"]
        + df["score_creative"]
        + df["score_social"]

    ) / 5


    df["logical_strength"] = (

        df["score_analytical"]
        + df["score_numeric"]

    ) / 2


    df["communication_strength"] = (

        df["score_verbal"]
        + df["score_social"]

    ) / 2


    df["creative_strength"] = (

        df["score_creative"]
        + df["score_verbal"]

    ) / 2


    # --------------------------------------------------------
    # Career-related features
    # --------------------------------------------------------

    df["technology_strength"] = (

        df["grade_cs"]
        + df["score_analytical"]
        + df["score_numeric"]
        + df["hobby_coding"] * 100
        + df["hobby_robotics"] * 100

    ) / 5


    df["science_strength"] = (

        df["grade_science"]
        + df["score_analytical"]
        + df["score_numeric"]
        + df["hobby_science_experiments"] * 100

    ) / 4


    df["business_strength"] = (

        df["score_numeric"]
        + df["score_social"]
        + df["score_verbal"]
        + df["hobby_business_trading"] * 100

    ) / 4


    df["creative_strength_combined"] = (

        df["score_creative"]
        + df["grade_lang"]
        + df["hobby_drawing_art"] * 100
        + df["hobby_music"] * 100
        + df["hobby_writing"] * 100
        + df["hobby_fashion"] * 100

    ) / 6


    df["social_strength"] = (

        df["score_social"]
        + df["score_verbal"]
        + df["grade_social"]
        + df["hobby_debating"] * 100
        + df["hobby_volunteering"] * 100

    ) / 5


    # --------------------------------------------------------
    # Hobby count
    # --------------------------------------------------------

    df["hobby_count"] = df[hobby_columns].sum(axis=1)


    # --------------------------------------------------------
    # Overall strength
    # --------------------------------------------------------

    df["overall_strength"] = (

        df["academic_average"]
        + df["aptitude_average"]

    ) / 2


    return df


# ============================================================
# FIELD-BASED CAREER BOOST
# ============================================================
#
# The current ranking model was trained with 40 numerical
# features and does NOT contain field_filter.
#
# Therefore, we apply a small field compatibility boost here.
#
# This makes changing the selected field actually influence
# the final ranking.
# ============================================================

field_keywords = {

    "Engineering": [

        "engineer",
        "architect",
        "technician"

    ],

    "Medical & Healthcare": [

        "doctor",
        "nurse",
        "medical",
        "physiotherapist",
        "psychologist",
        "health",
        "laboratory"

    ],

    "Business & Finance": [

        "accountant",
        "manager",
        "marketing",
        "business",
        "finance",
        "financial",
        "trading",
        "operations",
        "human resource",
        "hr",
        "economist"

    ],

    "Science & Research": [

        "scientist",
        "research",
        "physicist",
        "chemist",
        "biologist",
        "astronomer",
        "mathematician",
        "statistician",
        "geologist",
        "oceanographer",
        "ocean",
        "space"

    ],

    "Arts & Design": [

        "designer",
        "artist",
        "animator",
        "fashion",
        "interior",
        "vfx",
        "illustrator",
        "drawing"

    ],

    "Computer Science & IT": [

        "software",
        "developer",
        "programmer",
        "data scientist",
        "data analyst",
        "machine learning",
        "ai engineer",
        "cloud engineer",
        "devops",
        "network engineer",
        "cyber",
        "forensics",
        "web developer",
        "game developer",
        "it project"

    ],

    "Education": [

        "teacher",
        "professor",
        "trainer",
        "education",
        "special education",
        "instructor"

    ],

    "Law & Government": [

        "lawyer",
        "advocate",
        "government",
        "officer",
        "naval",
        "coast guard",
        "crime",
        "forensic"

    ],

    "Media & Communication": [

        "journalist",
        "writer",
        "content",
        "editor",
        "film",
        "director",
        "media",
        "public relations",
        "social media",
        "video"

    ],

    "Sports & Fitness": [

        "coach",
        "fitness",
        "sports",
        "physiotherapist",
        "yoga",
        "athlete"

    ]

}


def apply_field_boost(results, selected_field):

    keywords = field_keywords.get(
        selected_field,
        []
    )

    def calculate_boost(career):

        career_text = str(career).lower()

        for keyword in keywords:

            if keyword.lower() in career_text:

                return 0.20

        return 0.0


    results["Field_Boost"] = results["Career"].apply(
        calculate_boost
    )


    results["Final_Score"] = (

        results["Score"]
        + results["Field_Boost"]

    )


    return results


# ============================================================
# PREDICTION
# ============================================================

st.divider()


if st.button(

    "🔮 Predict Top 5 Careers",

    use_container_width=True,

    type="primary"

):

    try:

        # ----------------------------------------------------
        # CREATE FEATURES
        # ----------------------------------------------------

        student_df = create_features(student)


        # ----------------------------------------------------
        # CHECK FEATURES
        # ----------------------------------------------------

        missing_features = [

            col

            for col in feature_columns

            if col not in student_df.columns

        ]


        if missing_features:

            st.error(
                "❌ Some model features are missing."
            )

            st.write(missing_features)

            st.stop()


        # ----------------------------------------------------
        # EXACT FEATURE ORDER
        # ----------------------------------------------------

        X = student_df[
            feature_columns
        ].copy()


        X_processed = X.values


        # ----------------------------------------------------
        # MODEL PROBABILITIES
        # ----------------------------------------------------

        probabilities = ranking_model.predict_proba(
            X_processed
        )[0]


        classes = ranking_model.classes_


        # ----------------------------------------------------
        # CREATE RESULTS
        # ----------------------------------------------------

        results = pd.DataFrame({

            "Career": classes,

            "Score": probabilities

        })


        # ====================================================
        # REMOVE NOT_RECOMMENDED
        # ====================================================

        results = results[

            results["Career"].astype(str).str.upper()
            != "NOT_RECOMMENDED"

        ].copy()


        # ----------------------------------------------------
        # NORMALIZE MODEL SCORES
        # ----------------------------------------------------

        total_score = results["Score"].sum()


        if total_score > 0:

            results["Score"] = (
                results["Score"]
                / total_score
            )


        # ----------------------------------------------------
        # APPLY FIELD BOOST
        # ----------------------------------------------------

        results = apply_field_boost(
            results,
            field
        )


        # ----------------------------------------------------
        # SORT FINAL RESULTS
        # ----------------------------------------------------

        results = results.sort_values(

            by="Final_Score",

            ascending=False

        ).reset_index(drop=True)


        # ----------------------------------------------------
        # NORMALIZE FINAL SCORES
        # ----------------------------------------------------

        total_final = results["Final_Score"].sum()


        if total_final > 0:

            results["Final_Score"] = (

                results["Final_Score"]
                / total_final

            )


        # ----------------------------------------------------
        # TOP 5
        # ----------------------------------------------------

        top_5 = results.head(5).copy()

        top_5 = top_5.reset_index(drop=True)


        # ====================================================
        # DISPLAY
        # ====================================================

        st.subheader(
            "🏆 Your Top 5 Career Recommendations"
        )


        st.write(

            f"Recommendations are based on your "
            f"**{field}** field, hobbies, grades and "
            f"aptitude scores."

        )


        # ====================================================
        # CAREER CARDS
        # ====================================================

        for i in range(len(top_5)):

            career = top_5.loc[
                i,
                "Career"
            ]

            score = top_5.loc[
                i,
                "Final_Score"
            ] * 100


            if i == 0:

                st.success(

                    f"🥇 **1. {career}**\n\n"
                    f"Suitability Score: **{score:.2f}%**"

                )


            elif i == 1:

                st.info(

                    f"🥈 **2. {career}**\n\n"
                    f"Suitability Score: **{score:.2f}%**"

                )


            elif i == 2:

                st.warning(

                    f"🥉 **3. {career}**\n\n"
                    f"Suitability Score: **{score:.2f}%**"

                )


            else:

                st.write(
                    f"### {i + 1}. {career}"
                )


                st.progress(

                    min(
                        float(
                            top_5.loc[
                                i,
                                "Final_Score"
                            ]
                        ),
                        1.0
                    )

                )


                st.write(

                    f"Suitability Score: "
                    f"**{score:.2f}%**"

                )


        # ====================================================
        # SUMMARY TABLE
        # ====================================================

        st.divider()

        st.subheader(
            "📊 Ranking Summary"
        )


        display_results = top_5[

            [
                "Career",
                "Final_Score"
            ]

        ].copy()


        display_results.insert(

            0,

            "Rank",

            range(
                1,
                len(display_results) + 1
            )

        )


        display_results["Final_Score"] = (

            display_results["Final_Score"]
            * 100

        ).round(2)


        display_results = (
            display_results
            .rename(
                columns={
                    "Final_Score":
                    "Suitability (%)"
                }
            )
        )


        st.dataframe(

            display_results,

            use_container_width=True,

            hide_index=True

        )


        # ====================================================
        # DEBUG / INFORMATION
        # ====================================================

        with st.expander(
            "🔍 See Recommendation Details"
        ):

            st.write(
                "Selected Field:",
                field
            )

            st.write(
                "Number of careers evaluated:",
                len(results)
            )

            st.write(
                "NOT_RECOMMENDED removed:",
                "Yes"
            )


    except Exception as e:

        st.error(
            "❌ Prediction failed."
        )

        st.code(
            str(e)
        )

Overwriting app.py

In [2]:
%%writefile app.py

Overwriting app.py

In [136]:
import joblib

ranking_data = joblib.load("career_ranking_model.pkl")

print(type(ranking_data))

if isinstance(ranking_data, dict):
    print("Ranking model keys:")
    print(list(ranking_data.keys()))

<class 'dict'>
Ranking model keys:
['model', 'feature_columns', 'rank_weights']

In [137]:
print(ranking_data)

{'model': HistGradientBoostingClassifier(early_stopping=True, l2_regularization=1.5,
                               learning_rate=0.035, max_iter=600,
                               min_samples_leaf=5, random_state=42), 'feature_columns': ['hobby_coding', 'hobby_gaming', 'hobby_reading', 'hobby_writing', 'hobby_music', 'hobby_drawing_art', 'hobby_sports', 'hobby_cooking', 'hobby_photography', 'hobby_travel', 'hobby_science_experiments', 'hobby_volunteering', 'hobby_debating', 'hobby_robotics', 'hobby_fashion', 'hobby_business_trading', 'grade_math', 'grade_science', 'grade_lang', 'grade_social', 'grade_cs', 'score_analytical', 'score_numeric', 'score_verbal', 'score_creative', 'score_social', 'academic_average', 'stem_average', 'language_social_average', 'aptitude_average', 'logical_strength', 'communication_strength', 'creative_strength', 'technology_strength', 'science_strength', 'business_strength', 'creative_strength_combined', 'social_strength', 'hobby_count', 'overall_strength'], 'rank_weights': {'top_career_1': 5.0, 'top_career_2': 4.0, 'top_career_3': 3.0, 'top_career_4': 2.0, 'top_career_5': 1.0}}

In [138]:
import joblib

ranking_data = joblib.load("career_ranking_model.pkl")

print("Model:", ranking_data["model"])
print("Number of ranking features:", len(ranking_data["feature_columns"]))
print("Rank weights:", ranking_data["rank_weights"])

Model: HistGradientBoostingClassifier(early_stopping=True, l2_regularization=1.5,
                               learning_rate=0.035, max_iter=600,
                               min_samples_leaf=5, random_state=42)
Number of ranking features: 40
Rank weights: {'top_career_1': 5.0, 'top_career_2': 4.0, 'top_career_3': 3.0, 'top_career_4': 2.0, 'top_career_5': 1.0}

In [134]:
!streamlit run app.py &>/content/streamlit.log &

!cloudflared tunnel --url http://localhost:8501

2026-08-31T05:16:44Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-08-31T05:16:44Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-08-31T05:16:48Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T05:16:48Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-08-31T05:16:48Z INF |  https://cholesterol-concentrate-boating-mouth.trycloudflare.com                           |
2026-08-31T05:16:48Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T05:16:48Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-08-31T05:16:48Z INF Version 2026.8.2 (Checksum fcfb02b575a52ca1af2e3267af4e1517bcdeb30ac48c834c69abaed3c0576ad2)
2026-08-31T05:16:48Z INF GOOS: linux, GOVersion: go1.26.4, GoArch: amd64
2026-08-31T05:16:48Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-08-31T05:16:48Z INF cloudflared will not automatically update if installed by a package manager.
2026-08-31T05:16:48Z INF Generated Connector ID: 477c7060-423a-4fca-bb40-e11515d4d43a
2026-08-31T05:16:48Z INF Initial protocol quic
2026-08-31T05:16:48Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T05:16:48Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-08-31T05:16:48Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T05:16:48Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-08-31T05:16:48Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026/08/31 05:16:48 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-08-31T05:16:48Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.192.27
2026-08-31T05:16:48Z INF Registered tunnel connection connIndex=0 connection=8b6af926-7d1b-41c3-a67f-54ebc37ee831 event=0 ip=198.41.192.27 location=lax05 protocol=quic
2026-08-31T05:16:54Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:16:54Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-08-31T05:16:54Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:16:54Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-08-31T05:16:54Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-08-31T05:16:54Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-08-31T05:16:54Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-08-31T05:16:54Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-08-31T05:16:54Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-08-31T05:16:54Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-08-31T05:16:54Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-08-31T05:16:54Z INF |                                                                                     |
2026-08-31T05:16:54Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-08-31T05:16:54Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:16:54Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=cf7e6eaf-651a-4668-8cb0-f1daaa666ed4 status=pass target=region1.v2.argotunnel.com
2026-08-31T05:16:54Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=cf7e6eaf-651a-4668-8cb0-f1daaa666ed4 status=pass target=region2.v2.argotunnel.com
2026-08-31T05:16:54Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=cf7e6eaf-651a-4668-8cb0-f1daaa666ed4 status=pass target=region1.v2.argotunnel.com
2026-08-31T05:16:54Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=cf7e6eaf-651a-4668-8cb0-f1daaa666ed4 status=pass target=region2.v2.argotunnel.com
2026-08-31T05:16:54Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=cf7e6eaf-651a-4668-8cb0-f1daaa666ed4 status=pass target=region1.v2.argotunnel.com
2026-08-31T05:16:54Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=cf7e6eaf-651a-4668-8cb0-f1daaa666ed4 status=pass target=region2.v2.argotunnel.com
2026-08-31T05:16:54Z INF precheck component="Cloudflare API" details="API is reachable" run_id=cf7e6eaf-651a-4668-8cb0-f1daaa666ed4 status=pass target=api.cloudflare.com:443
2026-08-31T05:16:54Z INF precheck complete hard_fail=false run_id=cf7e6eaf-651a-4668-8cb0-f1daaa666ed4 suggested_protocol=quic
2026-08-31T05:21:39Z INF Initiating graceful shutdown due to signal interrupt ...
^C

In [129]:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

Selecting previously unselected package cloudflared.
(Reading database ... 118419 files and directories currently installed.)
Preparing to unpack cloudflared-linux-amd64.deb ...
Unpacking cloudflared (2026.8.2) ...
Setting up cloudflared (2026.8.2) ...
Processing triggers for man-db (2.10.2-1) ...

In [130]:
!cloudflared --version

cloudflared version 2026.8.2 (built 2026-08-14-12:17 UTC)

In [131]:
!streamlit run app.py &>/content/streamlit.log &

In [132]:
!cloudflared tunnel --url http://localhost:8501

2026-08-31T05:13:14Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-08-31T05:13:14Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-08-31T05:13:17Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T05:13:17Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-08-31T05:13:17Z INF |  https://arena-programmer-hear-duration.trycloudflare.com                                  |
2026-08-31T05:13:17Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T05:13:17Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-08-31T05:13:17Z INF Version 2026.8.2 (Checksum fcfb02b575a52ca1af2e3267af4e1517bcdeb30ac48c834c69abaed3c0576ad2)
2026-08-31T05:13:17Z INF GOOS: linux, GOVersion: go1.26.4, GoArch: amd64
2026-08-31T05:13:17Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-08-31T05:13:17Z INF cloudflared will not automatically update if installed by a package manager.
2026-08-31T05:13:17Z INF Generated Connector ID: d7cfc77a-7cc2-4908-8c3b-d0c15235338a
2026-08-31T05:13:17Z INF Initial protocol quic
2026-08-31T05:13:17Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T05:13:17Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/08/31 05:13:17 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-08-31T05:13:17Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T05:13:17Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-08-31T05:13:17Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-08-31T05:13:17Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.200.113
2026-08-31T05:13:18Z INF Registered tunnel connection connIndex=0 connection=811c9477-da31-4692-b1c6-b4f537a76e2a event=0 ip=198.41.200.113 location=phx01 protocol=quic
2026-08-31T05:13:23Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:13:23Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-08-31T05:13:23Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:13:23Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-08-31T05:13:23Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-08-31T05:13:23Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-08-31T05:13:23Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-08-31T05:13:23Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-08-31T05:13:23Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-08-31T05:13:23Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-08-31T05:13:23Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-08-31T05:13:23Z INF |                                                                                     |
2026-08-31T05:13:23Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-08-31T05:13:23Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:13:23Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=c7473999-2cbc-4750-a35a-f2c31788d3e6 status=pass target=region1.v2.argotunnel.com
2026-08-31T05:13:23Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=c7473999-2cbc-4750-a35a-f2c31788d3e6 status=pass target=region2.v2.argotunnel.com
2026-08-31T05:13:23Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=c7473999-2cbc-4750-a35a-f2c31788d3e6 status=pass target=region1.v2.argotunnel.com
2026-08-31T05:13:23Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=c7473999-2cbc-4750-a35a-f2c31788d3e6 status=pass target=region2.v2.argotunnel.com
2026-08-31T05:13:23Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=c7473999-2cbc-4750-a35a-f2c31788d3e6 status=pass target=region1.v2.argotunnel.com
2026-08-31T05:13:23Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=c7473999-2cbc-4750-a35a-f2c31788d3e6 status=pass target=region2.v2.argotunnel.com
2026-08-31T05:13:23Z INF precheck component="Cloudflare API" details="API is reachable" run_id=c7473999-2cbc-4750-a35a-f2c31788d3e6 status=pass target=api.cloudflare.com:443
2026-08-31T05:13:23Z INF precheck complete hard_fail=false run_id=c7473999-2cbc-4750-a35a-f2c31788d3e6 suggested_protocol=quic
2026-08-31T05:15:14Z INF Initiating graceful shutdown due to signal interrupt ...
2026-08-31T05:15:14Z ERR failed to run the datagram handler error="context canceled" connIndex=0 event=0 ip=198.41.200.113
2026-08-31T05:15:14Z ERR failed to serve tunnel connection error="accept stream listener encountered a failure while serving" connIndex=0 event=0 ip=198.41.200.113
2026-08-31T05:15:14Z ERR Serve tunnel error error="accept stream listener encountered a failure while serving" connIndex=0 event=0 ip=198.41.200.113
2026-08-31T05:15:14Z INF Retrying connection in up to 1s connIndex=0 event=0 ip=198.41.200.113
2026-08-31T05:15:14Z ERR Connection terminated connIndex=0
2026-08-31T05:15:14Z ERR no more connections active and exiting
2026-08-31T05:15:14Z INF Tunnel server stopped
2026-08-31T05:15:14Z INF Metrics server stopped

In [96]:
import os

print(os.path.exists("app.py"))
print(os.listdir())

True
['.config', 'career_training_data_cleaned (2).csv', 'career_training_data_cleaned (1).csv', 'career_recommendation_model.pkl', 'career_training_data_cleaned (4).csv', 'career_training_data_cleaned (3).csv', 'app.py', 'career_training_data_cleaned.csv', 'career_training_data_cleaned (5).csv', 'sample_data']

In [97]:
!streamlit run app.py --server.port 8501 &>/content/streamlit.log &

In [98]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-08-31 04:47:58.301 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.16.167.169:8501

In [99]:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /content/cloudflared
!chmod +x /content/cloudflared

In [100]:
!pkill -f cloudflared || true

^C

In [101]:
!nohup /content/cloudflared tunnel --url http://localhost:8501 > /content/cloudflared.log 2>&1 &

In [102]:
!cat /content/cloudflared.log

2026-08-31T04:48:16Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-08-31T04:48:16Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-08-31T04:48:19Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T04:48:19Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-08-31T04:48:19Z INF |  https://musical-arnold-humidity-copper.trycloudflare.com                                  |
2026-08-31T04:48:19Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T04:48:19Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-08-31T04:48:19Z INF Version 2026.8.2 (Checksum fcfb02b575a52ca1af2e3267af4e1517bcdeb30ac48c834c69abaed3c0576ad2)
2026-08-31T04:48:19Z INF GOOS: linux, GOVersion: go1.26.4, GoArch: amd64
2026-08-31T04:48:19Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-08-31T04:48:19Z INF Autoupdate frequency is set autoupdateFreq=86400000
2026-08-31T04:48:19Z INF Generated Connector ID: 5cb21559-489a-45d7-8251-e0ba892ef549
2026-08-31T04:48:19Z INF Initial protocol quic
2026-08-31T04:48:19Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T04:48:19Z INF ICMP proxy will use ::1 in zone lo as source for IPv6

In [103]:
import os

print("Model file exists:", os.path.exists("career_recommendation_model.pkl"))
print("App file exists:", os.path.exists("app.py"))

Model file exists: True
App file exists: True

In [104]:
import joblib

model_data = joblib.load("career_recommendation_model.pkl")

print(type(model_data))

if isinstance(model_data, dict):
    print("Saved objects:")
    for key, value in model_data.items():
        print(key, type(value))

<class 'dict'>
Saved objects:
models <class 'dict'>
field_encoder <class 'sklearn.preprocessing._encoders.OneHotEncoder'>
feature_columns <class 'list'>
base_features <class 'list'>
new_features <class 'list'>
career_columns <class 'list'>
accuracies <class 'dict'>

In [105]:
import joblib

joblib.dump(
    tuned_models,
    "career_recommendation_model.pkl"
)

print("New tuned model saved successfully!")

New tuned model saved successfully!

In [106]:
import os

print(
    "Model size:",
    os.path.getsize("career_recommendation_model.pkl"),
    "bytes"
)

Model size: 132525295 bytes

In [107]:
!pkill -f "streamlit run" || true

^C

In [108]:
!nohup streamlit run app.py --server.port 8501 > /content/streamlit.log 2>&1 &

In [109]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-08-31 04:49:42.930 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.16.167.169:8501

In [110]:
!pkill -f cloudflared || true
!nohup /content/cloudflared tunnel --url http://localhost:8501 > /content/cloudflared.log 2>&1 &

^C

In [111]:
!cat /content/cloudflared.log

2026-08-31T04:49:46Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-08-31T04:49:46Z INF Requesting new quick Tunnel on trycloudflare.com...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2026-08-31T04:49:46Z INF Unregistered tunnel connection connIndex=0 event=0 ip=198.41.200.43

In [112]:
import joblib

data = joblib.load("career_recommendation_model.pkl")

print("Saved model type:", type(data))

if isinstance(data, dict):
    print("Keys:", list(data.keys()))

Saved model type: <class 'dict'>
Keys: ['top_career_1', 'top_career_2', 'top_career_3', 'top_career_4', 'top_career_5']

In [113]:
import joblib

# Load your existing saved models
models = joblib.load("career_recommendation_model.pkl")

# Put them inside the structure expected by app.py
data = {
    "models": models
}

# Save corrected file
joblib.dump(
    data,
    "career_recommendation_model.pkl"
)

print("============================================================")
print("MODEL FILE FIXED")
print("============================================================")
print("Keys:", list(data.keys()))
print("Models:", list(data["models"].keys()))
print("============================================================")

============================================================
MODEL FILE FIXED
============================================================
Keys: ['models']
Models: ['top_career_1', 'top_career_2', 'top_career_3', 'top_career_4', 'top_career_5']
============================================================

In [114]:
import joblib

data = joblib.load("career_recommendation_model.pkl")

print("Keys:", list(data.keys()))
print("Model keys:", list(data["models"].keys()))

Keys: ['models']
Model keys: ['top_career_1', 'top_career_2', 'top_career_3', 'top_career_4', 'top_career_5']

In [115]:
!pkill -f "streamlit run" || true

^C

In [116]:
!nohup streamlit run app.py --server.port 8501 > /content/streamlit.log 2>&1 &

In [117]:
!cat /content/streamlit.log

In [118]:
import joblib

# Save everything the Streamlit app needs
model_data = {
    "models": tuned_models,
    "field_encoder": field_encoder
}

joblib.dump(
    model_data,
    "career_recommendation_model.pkl"
)

print("=" * 60)
print("COMPLETE MODEL PACKAGE SAVED")
print("=" * 60)
print("Keys:", list(model_data.keys()))
print("Models:", list(model_data["models"].keys()))
print("Field encoder:", type(model_data["field_encoder"]))
print("=" * 60)

============================================================
COMPLETE MODEL PACKAGE SAVED
============================================================
Keys: ['models', 'field_encoder']
Models: ['top_career_1', 'top_career_2', 'top_career_3', 'top_career_4', 'top_career_5']
Field encoder: <class 'sklearn.preprocessing._encoders.OneHotEncoder'>
============================================================

In [119]:
data = joblib.load("career_recommendation_model.pkl")

print("Keys:", list(data.keys()))

Keys: ['models', 'field_encoder']

In [120]:
!pkill -f "streamlit run" || true

^C

In [121]:
!nohup streamlit run app.py --server.port 8501 > /content/streamlit.log 2>&1 &

In [122]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-08-31 04:51:30.335 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.16.167.169:8501

In [123]:
import joblib

model_data = {
    "models": tuned_models,
    "field_encoder": field_encoder,
    "feature_columns": feature_columns
}

joblib.dump(
    model_data,
    "career_recommendation_model.pkl"
)

print("=" * 60)
print("COMPLETE MODEL PACKAGE SAVED")
print("=" * 60)
print("Keys:", list(model_data.keys()))
print("Number of models:", len(model_data["models"]))
print("Number of features:", len(model_data["feature_columns"]))
print("Feature columns:")
print(model_data["feature_columns"])
print("=" * 60)

============================================================
COMPLETE MODEL PACKAGE SAVED
============================================================
Keys: ['models', 'field_encoder', 'feature_columns']
Number of models: 5
Number of features: 41
Feature columns:
['field_filter', 'hobby_coding', 'hobby_gaming', 'hobby_reading', 'hobby_writing', 'hobby_music', 'hobby_drawing_art', 'hobby_sports', 'hobby_cooking', 'hobby_photography', 'hobby_travel', 'hobby_science_experiments', 'hobby_volunteering', 'hobby_debating', 'hobby_robotics', 'hobby_fashion', 'hobby_business_trading', 'grade_math', 'grade_science', 'grade_lang', 'grade_social', 'grade_cs', 'score_analytical', 'score_numeric', 'score_verbal', 'score_creative', 'score_social', 'academic_average', 'stem_average', 'language_social_average', 'aptitude_average', 'logical_strength', 'communication_strength', 'creative_strength', 'technology_strength', 'science_strength', 'business_strength', 'creative_strength_combined', 'social_strength', 'hobby_count', 'overall_strength']
============================================================

In [124]:
data = joblib.load("career_recommendation_model.pkl")

print("Saved keys:", list(data.keys()))
print("Models:", list(data["models"].keys()))
print("Features:", len(data["feature_columns"]))

Saved keys: ['models', 'field_encoder', 'feature_columns']
Models: ['top_career_1', 'top_career_2', 'top_career_3', 'top_career_4', 'top_career_5']
Features: 41

In [125]:
print("=" * 60)
print("CAREER CLASS DISTRIBUTION")
print("=" * 60)

career_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]

for col in career_columns:
    print("\n" + col)
    print("-" * 40)
    print(df[col].value_counts().head(15))

============================================================
CAREER CLASS DISTRIBUTION
============================================================

top_career_1
----------------------------------------
top_career_1
IT Project Manager          160
Public Relations Manager    156
Accountant                  140
Network Engineer            117
Software Developer          108
Graphic Designer             73
Space Scientist              68
Sports Coach                 68
Research Scientist           66
Animator                     62
Physicist                    58
Civil Engineer               57
Doctor                       56
Social Welfare Officer       54
Hotel Manager                49
Name: count, dtype: int64

top_career_2
----------------------------------------
top_career_2
Chartered Accountant (CA)    140
Cloud Engineer               117
Web Developer                108
Data Scientist                95
Fashion Designer              83
Fitness Trainer               68
ISRO Scientist                68
Film Director                 62
School Teacher                60
Chemist                       58
Mechanical Engineer           57
Animator                      56
Nurse                         55
IT Project Manager            53
Lawyer / Advocate             49
Name: count, dtype: int64

top_career_3
----------------------------------------
top_career_3
Marketing Manager           135
AI Engineer                 117
Mobile App Developer        108
Interior Designer           105
Marine Biologist             73
Yoga Instructor              68
DRDO Scientist               68
Research Analyst             66
Video Editor                 62
Crime Scene Investigator     61
Mathematician                58
Professor                    58
Electrical Engineer          57
Film Director                56
Training Manager             55
Name: count, dtype: int64

top_career_4
----------------------------------------
top_career_4
Human Resource Manager       135
Machine Learning Engineer    117
Naval Architect               73
Astronomer                    68
Sports Physiotherapist        68
Laboratory Researcher         66
Game Developer                63
Journalist                    62
Forensic Psychologist         61
Social Media Manager          58
Statistician                  58
Special Education Teacher     58
Electronics Engineer          57
Video Editor                  56
Accountant                    55
Name: count, dtype: int64

top_career_5
----------------------------------------
top_career_5
Operations Manager               135
DevOps Engineer                  114
Oceanographer                     73
Aerospace Engineer                69
Sports Psychologist               68
Coast Guard Officer               67
Scientific Writer                 66
Fashion Stylist                   64
Software Tester / QA Engineer     63
Content Writer                    62
Digital Forensics Analyst         61
NGO Program Manager               59
Geologist                         58
VFX Artist                        58
Chemical Engineer                 57
Name: count, dtype: int64

In [139]:
# ============================================================
# IMPROVED CAREER RANKING MODEL
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


print("=" * 60)
print("BUILDING IMPROVED CAREER RANKING MODEL")
print("=" * 60)


# ============================================================
# 1. LOAD DATASET
# ============================================================

csv_files = [
    f for f in os.listdir(".")
    if f.endswith(".csv")
]

print("CSV files found:", csv_files)

if "career_training_data_cleaned.csv" in csv_files:
    csv_file = "career_training_data_cleaned.csv"
else:
    cleaned_files = [
        f for f in csv_files
        if f.startswith("career_training_data_cleaned")
    ]

    if not cleaned_files:
        raise FileNotFoundError(
            "Career CSV dataset not found."
        )

    csv_file = cleaned_files[0]

df = pd.read_csv(csv_file)

print("Dataset:", csv_file)
print("Shape:", df.shape)


# ============================================================
# 2. CAREER COLUMNS
# ============================================================

career_columns = [
    "top_career_1",
    "top_career_2",
    "top_career_3",
    "top_career_4",
    "top_career_5"
]


# ============================================================
# 3. FEATURE COLUMNS
# ============================================================

hobby_columns = [
    "hobby_coding",
    "hobby_gaming",
    "hobby_reading",
    "hobby_writing",
    "hobby_music",
    "hobby_drawing_art",
    "hobby_sports",
    "hobby_cooking",
    "hobby_photography",
    "hobby_travel",
    "hobby_science_experiments",
    "hobby_volunteering",
    "hobby_debating",
    "hobby_robotics",
    "hobby_fashion",
    "hobby_business_trading"
]


grade_columns = [
    "grade_math",
    "grade_science",
    "grade_lang",
    "grade_social",
    "grade_cs"
]


score_columns = [
    "score_analytical",
    "score_numeric",
    "score_verbal",
    "score_creative",
    "score_social"
]


# ============================================================
# 4. FEATURE ENGINEERING
# ============================================================

df_model = df.copy()


# ------------------------------------------------------------
# Academic features
# ------------------------------------------------------------

df_model["academic_average"] = (
    df_model["grade_math"]
    + df_model["grade_science"]
    + df_model["grade_lang"]
    + df_model["grade_social"]
    + df_model["grade_cs"]
) / 5


df_model["stem_average"] = (
    df_model["grade_math"]
    + df_model["grade_science"]
    + df_model["grade_cs"]
) / 3


df_model["language_social_average"] = (
    df_model["grade_lang"]
    + df_model["grade_social"]
) / 2


# ------------------------------------------------------------
# Aptitude features
# ------------------------------------------------------------

df_model["aptitude_average"] = (
    df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["score_verbal"]
    + df_model["score_creative"]
    + df_model["score_social"]
) / 5


df_model["logical_strength"] = (
    df_model["score_analytical"]
    + df_model["score_numeric"]
) / 2


df_model["communication_strength"] = (
    df_model["score_verbal"]
    + df_model["score_social"]
) / 2


df_model["creative_strength"] = (
    df_model["score_creative"]
    + df_model["score_verbal"]
) / 2


# ------------------------------------------------------------
# Career-related features
# ------------------------------------------------------------

df_model["technology_strength"] = (
    df_model["grade_cs"]
    + df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["hobby_coding"] * 100
    + df_model["hobby_robotics"] * 100
) / 5


df_model["science_strength"] = (
    df_model["grade_science"]
    + df_model["score_analytical"]
    + df_model["score_numeric"]
    + df_model["hobby_science_experiments"] * 100
) / 4


df_model["business_strength"] = (
    df_model["score_numeric"]
    + df_model["score_social"]
    + df_model["score_verbal"]
    + df_model["hobby_business_trading"] * 100
) / 4


df_model["creative_strength_combined"] = (
    df_model["score_creative"]
    + df_model["grade_lang"]
    + df_model["hobby_drawing_art"] * 100
    + df_model["hobby_music"] * 100
    + df_model["hobby_writing"] * 100
    + df_model["hobby_fashion"] * 100
) / 6


df_model["social_strength"] = (
    df_model["score_social"]
    + df_model["score_verbal"]
    + df_model["grade_social"]
    + df_model["hobby_debating"] * 100
    + df_model["hobby_volunteering"] * 100
) / 5


# ------------------------------------------------------------
# Hobby count
# ------------------------------------------------------------

df_model["hobby_count"] = (
    df_model[hobby_columns].sum(axis=1)
)


# ------------------------------------------------------------
# Overall strength
# ------------------------------------------------------------

df_model["overall_strength"] = (
    df_model["academic_average"]
    + df_model["aptitude_average"]
) / 2


# ============================================================
# 5. RANKING FEATURES
# ============================================================

ranking_features = (
    hobby_columns
    + grade_columns
    + score_columns
    + [
        "academic_average",
        "stem_average",
        "language_social_average",
        "aptitude_average",
        "logical_strength",
        "communication_strength",
        "creative_strength",
        "technology_strength",
        "science_strength",
        "business_strength",
        "creative_strength_combined",
        "social_strength",
        "hobby_count",
        "overall_strength"
    ]
)


X = df_model[ranking_features].copy()


print()
print("=" * 60)
print("FEATURE ENGINEERING COMPLETE")
print("=" * 60)

print("Total ranking features:", len(ranking_features))
print("Processed shape:", X.shape)


# ============================================================
# 6. CREATE CAREER SCORES
# ============================================================

print()
print("=" * 60)
print("CREATING CAREER SUITABILITY DATA")
print("=" * 60)


# Rank weights
rank_weights = {
    "top_career_1": 5.0,
    "top_career_2": 4.0,
    "top_career_3": 3.0,
    "top_career_4": 2.0,
    "top_career_5": 1.0
}


# Create unique career list
all_careers = set()

for column in career_columns:

    all_careers.update(
        df_model[column]
        .dropna()
        .astype(str)
        .unique()
    )


all_careers = sorted(list(all_careers))

print("Unique careers:", len(all_careers))


# ============================================================
# 7. CREATE TRAINING ROWS
# ============================================================

training_X = []
training_y = []
training_weights = []


for i in range(len(df_model)):

    student_features = X.iloc[i].values

    for career in all_careers:

        score = 0.0

        # ----------------------------------------------------
        # Find career position
        # ----------------------------------------------------

        for column in career_columns:

            value = df_model.iloc[i][column]

            if pd.isna(value):
                continue

            if str(value) == career:

                score = rank_weights[column]
                break


        # ----------------------------------------------------
        # Positive examples
        # ----------------------------------------------------

        if score > 0:

            training_X.append(
                student_features
            )

            training_y.append(
                career
            )

            training_weights.append(
                score
            )


        # ----------------------------------------------------
        # Negative examples
        # ----------------------------------------------------
        # Add some careers that were NOT recommended.
        #
        # This helps the model learn the difference between
        # suitable and unsuitable careers.
        # ----------------------------------------------------

        else:

            # deterministic selection
            if (
                hash(
                    str(i) + career
                ) % 12 == 0
            ):

                training_X.append(
                    student_features
                )

                training_y.append(
                    "__NOT_RECOMMENDED__"
                )

                training_weights.append(
                    0.2
                )


training_X = np.array(training_X)

training_y = np.array(training_y)

training_weights = np.array(
    training_weights
)


print(
    "Training samples:",
    len(training_X)
)

print(
    "Training classes:",
    len(np.unique(training_y))
)


# ============================================================
# 8. TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test, w_train, w_test = (
    train_test_split(
        training_X,
        training_y,
        training_weights,
        test_size=0.20,
        random_state=42,
        stratify=training_y
    )
)


# ============================================================
# 9. TRAIN MODEL
# ============================================================

print()
print("=" * 60)
print("TRAINING IMPROVED RANKING MODEL")
print("=" * 60)


ranking_model = HistGradientBoostingClassifier(
    max_iter=600,
    learning_rate=0.035,
    max_leaf_nodes=31,
    min_samples_leaf=5,
    l2_regularization=1.5,
    early_stopping=True,
    random_state=42
)


ranking_model.fit(
    X_train,
    y_train,
    sample_weight=w_train
)


# ============================================================
# 10. TEST
# ============================================================

pred = ranking_model.predict(
    X_test
)


accuracy = accuracy_score(
    y_test,
    pred
)


print()
print("=" * 60)
print("MODEL RESULTS")
print("=" * 60)

print(
    f"Classification accuracy: "
    f"{accuracy * 100:.2f}%"
)


# ============================================================
# 11. SAVE MODEL
# ============================================================

ranking_package = {

    "model": ranking_model,

    "feature_columns": ranking_features,

    "career_list": all_careers,

    "rank_weights": rank_weights,

    "accuracy": accuracy
}


joblib.dump(
    ranking_package,
    "career_ranking_model.pkl"
)


print()
print("=" * 60)
print("RANKING MODEL SAVED")
print("=" * 60)

print(
    "File: career_ranking_model.pkl"
)

print(
    "Features:",
    len(ranking_features)
)

print(
    "Careers:",
    len(all_careers)
)

print(
    f"Accuracy: "
    f"{accuracy * 100:.2f}%"
)

print("=" * 60)

============================================================
BUILDING IMPROVED CAREER RANKING MODEL
============================================================
CSV files found: ['career_training_data_cleaned (2).csv', 'career_training_data_cleaned (1).csv', 'career_training_data_cleaned (4).csv', 'career_training_data_cleaned (3).csv', 'career_training_data_cleaned.csv', 'career_training_data_cleaned (5).csv']
Dataset: career_training_data_cleaned.csv
Shape: (2000, 32)

============================================================
FEATURE ENGINEERING COMPLETE
============================================================
Total ranking features: 40
Processed shape: (2000, 40)

============================================================
CREATING CAREER SUITABILITY DATA
============================================================
Unique careers: 141
Training samples: 32677
Training classes: 142

============================================================
TRAINING IMPROVED RANKING MODEL
============================================================

============================================================
MODEL RESULTS
============================================================
Classification accuracy: 13.74%

============================================================
RANKING MODEL SAVED
============================================================
File: career_ranking_model.pkl
Features: 40
Careers: 141
Accuracy: 13.74%
============================================================

In [144]:
!streamlit run app.py &>/content/streamlit.log &

In [145]:
!cloudflared tunnel --url http://localhost:8501

2026-08-31T05:47:03Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-08-31T05:47:03Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-08-31T05:47:07Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T05:47:07Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-08-31T05:47:07Z INF |  https://accordance-buffalo-choose-excel.trycloudflare.com                                 |
2026-08-31T05:47:07Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T05:47:07Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-08-31T05:47:07Z INF Version 2026.8.2 (Checksum fcfb02b575a52ca1af2e3267af4e1517bcdeb30ac48c834c69abaed3c0576ad2)
2026-08-31T05:47:07Z INF GOOS: linux, GOVersion: go1.26.4, GoArch: amd64
2026-08-31T05:47:07Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-08-31T05:47:07Z INF cloudflared will not automatically update if installed by a package manager.
2026-08-31T05:47:07Z INF Generated Connector ID: 0206f366-4049-4d84-985e-cc8879ddfc2b
2026-08-31T05:47:07Z INF Initial protocol quic
2026-08-31T05:47:07Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T05:47:07Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/08/31 05:47:07 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-08-31T05:47:07Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T05:47:07Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-08-31T05:47:07Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-08-31T05:47:07Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.192.57
2026-08-31T05:47:08Z INF Registered tunnel connection connIndex=0 connection=d70fedfc-f04c-4de1-a3f5-c91551c80a19 event=0 ip=198.41.192.57 location=lax05 protocol=quic
2026-08-31T05:47:13Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:47:13Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-08-31T05:47:13Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:47:13Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-08-31T05:47:13Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-08-31T05:47:13Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-08-31T05:47:13Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-08-31T05:47:13Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-08-31T05:47:13Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-08-31T05:47:13Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-08-31T05:47:13Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-08-31T05:47:13Z INF |                                                                                     |
2026-08-31T05:47:13Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-08-31T05:47:13Z INF +-------------------------------------------------------------------------------------+
2026-08-31T05:47:13Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=5369579e-a549-43fa-bee2-950ab04234ba status=pass target=region1.v2.argotunnel.com
2026-08-31T05:47:13Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=5369579e-a549-43fa-bee2-950ab04234ba status=pass target=region2.v2.argotunnel.com
2026-08-31T05:47:13Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=5369579e-a549-43fa-bee2-950ab04234ba status=pass target=region1.v2.argotunnel.com
2026-08-31T05:47:13Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=5369579e-a549-43fa-bee2-950ab04234ba status=pass target=region2.v2.argotunnel.com
2026-08-31T05:47:13Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=5369579e-a549-43fa-bee2-950ab04234ba status=pass target=region1.v2.argotunnel.com
2026-08-31T05:47:13Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=5369579e-a549-43fa-bee2-950ab04234ba status=pass target=region2.v2.argotunnel.com
2026-08-31T05:47:13Z INF precheck component="Cloudflare API" details="API is reachable" run_id=5369579e-a549-43fa-bee2-950ab04234ba status=pass target=api.cloudflare.com:443
2026-08-31T05:47:13Z INF precheck complete hard_fail=false run_id=5369579e-a549-43fa-bee2-950ab04234ba suggested_protocol=quic
2026-08-31T05:53:23Z INF Initiating graceful shutdown due to signal interrupt ...
2026-08-31T05:53:23Z ERR failed to run the datagram handler error="context canceled" connIndex=0 event=0 ip=198.41.192.57
2026-08-31T05:53:23Z ERR failed to serve tunnel connection error="accept stream listener encountered a failure while serving" connIndex=0 event=0 ip=198.41.192.57
2026-08-31T05:53:23Z ERR Serve tunnel error error="accept stream listener encountered a failure while serving" connIndex=0 event=0 ip=198.41.192.57
2026-08-31T05:53:23Z INF Retrying connection in up to 1s connIndex=0 event=0 ip=198.41.192.57
2026-08-31T05:53:23Z ERR Connection terminated connIndex=0
2026-08-31T05:53:23Z ERR no more connections active and exiting
2026-08-31T05:53:23Z INF Tunnel server stopped
2026-08-31T05:53:23Z INF Metrics server stopped

In [15]:
!pkill -f streamlit

In [16]:
!streamlit run app.py >/content/streamlit.log 2>&1 &

In [17]:
!sleep 3
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-08-31 06:16:44.643 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.16.167.169:8501

In [8]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-08-31 06:01:40.052 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.16.167.169:8501

In [18]:
!pkill -f streamlit
!pkill -f cloudflared

In [19]:
!streamlit run app.py >/content/streamlit.log 2>&1 &

In [20]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-08-31 06:17:29.468 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.16.167.169:8501

In [21]:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /content/cloudflared
!chmod +x /content/cloudflared

In [22]:
!/content/cloudflared tunnel --url http://localhost:8501

2026-08-31T06:17:38Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-08-31T06:17:38Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-08-31T06:17:41Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T06:17:41Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-08-31T06:17:41Z INF |  https://easy-throws-thickness-graphics.trycloudflare.com                                  |
2026-08-31T06:17:41Z INF +--------------------------------------------------------------------------------------------+
2026-08-31T06:17:41Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-08-31T06:17:41Z INF Version 2026.8.2 (Checksum fcfb02b575a52ca1af2e3267af4e1517bcdeb30ac48c834c69abaed3c0576ad2)
2026-08-31T06:17:41Z INF GOOS: linux, GOVersion: go1.26.4, GoArch: amd64
2026-08-31T06:17:41Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-08-31T06:17:41Z INF cloudflared will not automatically update if installed by a package manager.
2026-08-31T06:17:41Z INF Generated Connector ID: 008fa798-1ce5-4a10-a40c-6d085f4161dc
2026-08-31T06:17:41Z INF Initial protocol quic
2026-08-31T06:17:41Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T06:17:41Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/08/31 06:17:41 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-08-31T06:17:41Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-08-31T06:17:41Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-08-31T06:17:41Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-08-31T06:17:41Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.200.113
2026-08-31T06:17:42Z INF Registered tunnel connection connIndex=0 connection=cc1e043f-a52c-41ef-80f6-8f6d20f11303 event=0 ip=198.41.200.113 location=phx01 protocol=quic
2026-08-31T06:17:47Z INF +-------------------------------------------------------------------------------------+
2026-08-31T06:17:47Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-08-31T06:17:47Z INF +-------------------------------------------------------------------------------------+
2026-08-31T06:17:47Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-08-31T06:17:47Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-08-31T06:17:47Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-08-31T06:17:47Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-08-31T06:17:47Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-08-31T06:17:47Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-08-31T06:17:47Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-08-31T06:17:47Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-08-31T06:17:47Z INF |                                                                                     |
2026-08-31T06:17:47Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-08-31T06:17:47Z INF +-------------------------------------------------------------------------------------+
2026-08-31T06:17:47Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=778f4cdc-206f-455d-8f54-7c9163978a97 status=pass target=region1.v2.argotunnel.com
2026-08-31T06:17:47Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=778f4cdc-206f-455d-8f54-7c9163978a97 status=pass target=region2.v2.argotunnel.com
2026-08-31T06:17:47Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=778f4cdc-206f-455d-8f54-7c9163978a97 status=pass target=region1.v2.argotunnel.com
2026-08-31T06:17:47Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=778f4cdc-206f-455d-8f54-7c9163978a97 status=pass target=region2.v2.argotunnel.com
2026-08-31T06:17:47Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=778f4cdc-206f-455d-8f54-7c9163978a97 status=pass target=region1.v2.argotunnel.com
2026-08-31T06:17:47Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=778f4cdc-206f-455d-8f54-7c9163978a97 status=pass target=region2.v2.argotunnel.com
2026-08-31T06:17:47Z INF precheck component="Cloudflare API" details="API is reachable" run_id=778f4cdc-206f-455d-8f54-7c9163978a97 status=pass target=api.cloudflare.com:443
2026-08-31T06:17:47Z INF precheck complete hard_fail=false run_id=778f4cdc-206f-455d-8f54-7c9163978a97 suggested_protocol=quic
2026-08-31T07:15:42Z INF Initiating graceful shutdown due to signal interrupt ...
2026-08-31T07:15:42Z ERR failed to run the datagram handler error="context canceled" connIndex=0 event=0 ip=198.41.200.113
2026-08-31T07:15:42Z ERR failed to serve tunnel connection error="accept stream listener encountered a failure while serving" connIndex=0 event=0 ip=198.41.200.113
2026-08-31T07:15:42Z ERR Serve tunnel error error="accept stream listener encountered a failure while serving" connIndex=0 event=0 ip=198.41.200.113
2026-08-31T07:15:42Z INF Retrying connection in up to 1s connIndex=0 event=0 ip=198.41.200.113
2026-08-31T07:15:42Z ERR Connection terminated connIndex=0
2026-08-31T07:15:42Z ERR no more connections active and exiting
2026-08-31T07:15:42Z INF Tunnel server stopped
2026-08-31T07:15:42Z INF Metrics server stopped

In [23]:
from google.colab import files

files.download("app.py")
files.download("career_ranking_model.pkl")
files.download("career_recommendation_model.pkl")
files.download("career_training_data_cleaned.csv")